// category_constants.dart
import 'package:flutter/material.dart';
import 'package:flutter_sfsymbols/flutter_sfsymbols.dart';

// List<String> myCategoriesIcons = [
//   'airplane',
//   'archivebox.fill',
//   'bag.fill',
//   'bed.double.fill',
//   'bolt.fill',
//   'book.fill',
//   'briefcase.fill',
//   'car.fill',
//   'cart',
//   'chart.pie',
//   'creditcard.fill',
//   'drop.fill',
//   'exclamationmark.triangle.fill',
//   'film',
//   'flame.fill',
//   'gamecontroller.fill',
//   'gift.fill',
//   'hand.tap',
//   'heart.fill',
//   'house.fill',
//   'lock.fill',
//   'macbook',
//   'music.note.list',
//   'paintbrush.pointed.fill',
//   'phone.fill',
//   'play.fill',
//   'scissors',
//   'shield.fill',
//   'sparkles',
//   'ticket.fill',
//   'tram.fill',
//   'tv.fill',
//   'wrench.and.screwdriver.fill'
// ];

// final Map<String, IconData> iconMap = {
//   'airplane': SFSymbols.airplane,
//   'archivebox.fill': SFSymbols.archivebox_fill,
//   'bag.fill': SFSymbols.bag_fill,
//   'bed.double.fill': SFSymbols.bed_double_fill,
//   'bolt.fill': SFSymbols.bolt_fill,
//   'book.fill': SFSymbols.book_fill,
//   'briefcase.fill': SFSymbols.briefcase_fill,
//   'car.fill': SFSymbols.car_fill,
//   'cart': SFSymbols.cart_fill,
//   'chart.pie': SFSymbols.chart_pie_fill,
//   'creditcard.fill': SFSymbols.creditcard_fill,
//   'drop.fill': SFSymbols.drop_fill,
//   'exclamationmark.triangle.fill': SFSymbols.exclamationmark_triangle_fill,
//   'film': SFSymbols.film_fill,
//   'flame.fill': SFSymbols.flame_fill,
//   'gamecontroller.fill': SFSymbols.gamecontroller_fill,
//   'gift.fill': SFSymbols.gift_fill,
//   'hand.tap': SFSymbols.hand_draw,
//   'heart.fill': SFSymbols.heart_fill,
//   'house.fill': SFSymbols.house_fill,
//   'lock.fill': SFSymbols.lock_fill,
//   'macbook': SFSymbols.macwindow,
//   'music.note.list': SFSymbols.music_note_list,
//   'paintbrush.pointed.fill': SFSymbols.paintbrush_fill,
//   'phone.fill': SFSymbols.phone_fill,
//   'play.fill': SFSymbols.play_fill,
//   'scissors': SFSymbols.scissors,
//   'shield.fill': SFSymbols.shield_fill,
//   'sparkles': SFSymbols.sparkles,
//   'ticket.fill': SFSymbols.ticket_fill,
//   'tram.fill': SFSymbols.tram_fill,
//   'tv.fill': SFSymbols.tv_fill,
//   'wrench.and.screwdriver.fill': SFSymbols.wrench_fill,
// };

List<String> myCategoriesIcons = [
'alarm_fill',
'alt',
'ant_circle_fill',
'alarm',
'ant',
'app_badge_fill',
'ant_circle',
'ant_fill',
'antenna_radiowaves_left_right',
'archivebox_fill',
'app_fill',
'app_badge',
'arrow_2_circlepath_circle',
'app',
'arrow_2_circlepath_circle_fill',
'archivebox',
'arrow_2_circlepath',
'arrow_3_trianglepath',
'arrow_clockwise_circle',
'arrow_branch',
'arrow_2_squarepath',
'arrow_clockwise_circle_fill',
'arrow_clockwise',
'arrow_counterclockwise_circle',
'arrow_counterclockwise_circle_fill',
'arrow_down_circle',
'arrow_counterclockwise',
'arrow_down_circle_fill',
'arrow_down_left_circle_fill',
'arrow_down_doc_fill',
'arrow_down_doc',
'arrow_down_left_square',
'arrow_down_right_circle_fill',
'arrow_down_left',
'arrow_down_left_circle',
'arrow_down_left_square_fill',
'arrow_down_right_circle',
'arrow_down_right_square_fill',
'arrow_down_right_arrow_up_left',
'arrow_down_right_square',
'arrow_down_square',
'arrow_down_right',
'arrow_down',
'arrow_down_square_fill',
'arrow_down_to_line',
'arrow_left_circle_fill',
'arrow_left_right_circle_fill',
'arrow_left_circle',
'arrow_left_right_square',
'arrow_down_to_line_alt',
'arrow_left_right_square_fill',
'arrow_left_right_circle',
'arrow_left_right',
'arrow_left',
'arrow_left_square_fill',
'arrow_left_to_line_alt',
'arrow_right_arrow_left_circle',
'arrow_merge',
'arrow_left_to_line',
'arrow_right_arrow_left_circle_fill',
'arrow_left_square',
'arrow_right_arrow_left_square_fill',
'arrow_right_arrow_left',
'arrow_right_square_fill',
'arrow_right_circle',
'arrow_right_circle_fill',
'arrow_right_arrow_left_square',
'arrow_right_to_line',
'arrow_turn_down_left',
'arrow_right_to_line_alt',
'arrow_turn_left_up',
'arrow_swap',
'arrow_right',
'arrow_right_square',
'arrow_turn_left_down',
'arrow_turn_right_down',
'arrow_turn_up_left',
'arrow_turn_right_up',
'arrow_turn_up_right',
'arrow_up_arrow_down_circle',
'arrow_up_arrow_down_circle_fill',
'arrow_up_arrow_down_square_fill',
'arrow_up_bin_fill',
'arrow_up_arrow_down_square',
'arrow_up_bin',
'arrow_up_circle',
'arrow_turn_down_right',
'arrow_up_doc_fill',
'arrow_up_doc',
'arrow_up_arrow_down',
'arrow_up_down_square_fill',
'arrow_up_down_circle_fill',
'arrow_up_down_circle',
'arrow_up_down',
'arrow_up_left_arrow_down_right',
'arrow_up_circle_fill',
'arrow_up_down_square',
'arrow_up_left_circle_fill',
'arrow_up_left_square_fill',
'arrow_up_right_circle_fill',
'arrow_up_left_circle',
'arrow_up_left_square',
'arrow_up_right_diamond_fill',
'arrow_up_left',
'arrow_up_right_circle',
'arrow_up_right_diamond',
'arrow_up_right',
'arrow_up_right_square_fill',
'arrow_up_square_fill',
'arrow_up_to_line_alt',
'arrow_up_to_line',
'arrow_up_square',
'arrow_up_right_square',
'arrow_up',
'arrow_uturn_down_circle_fill',
'arrow_uturn_down_square',
'arrow_uturn_left_circle',
'arrow_uturn_down_square_fill',
'arrow_uturn_down',
'arrow_uturn_down_circle',
'arrow_uturn_left_circle_fill',
'arrow_uturn_left',
'arrow_uturn_left_square_fill',
'arrow_uturn_left_square',
'arrow_uturn_right_circle',
'arrow_uturn_right_square_fill',
'arrow_uturn_right_circle_fill',
'arrow_uturn_up_circle_fill',
'arrow_uturn_right',
'arrow_uturn_right_square',
'arrow_uturn_up_square',
'arrow_uturn_up_square_fill',
'arrow_uturn_up_circle',
'arrowshape_turn_up_left_2_fill',
'arrowshape_turn_up_left_circle_fill',
'arrow_uturn_up',
'arrowshape_turn_up_left_2',
'arrowshape_turn_up_left_fill',
'arrowshape_turn_up_left',
'arrowshape_turn_up_left_circle',
'arrowshape_turn_up_right_circle_fill',
'arrowshape_turn_up_right',
'arrowtriangle_down_circle_fill',
'arrowtriangle_down_square_fill',
'arrowtriangle_down_fill',
'arrowshape_turn_up_right_circle',
'arrowtriangle_down_circle',
'arrowtriangle_down',
'arrowtriangle_left_circle_fill',
'arrowshape_turn_up_right_fill',
'arrowtriangle_left_fill',
'arrowtriangle_left_square_fill',
'arrowtriangle_right_circle_fill',
'arrowtriangle_left',
'arrowtriangle_right_square_fill',
'arrowtriangle_down_square',
'arrowtriangle_left_square',
'arrowtriangle_right_fill',
'arrowtriangle_left_circle',
'arrowtriangle_right_circle',
'arrowtriangle_up_fill',
'arrowtriangle_right_square',
'arrowtriangle_up_circle',
'arrowtriangle_right',
'arrowtriangle_up_circle_fill',
'arrowtriangle_up_square_fill',
'arrowtriangle_up',
'arrowtriangle_up_square',
'asterisk_circle_fill',
'asterisk_circle',
'at_circle_fill',
'at_badge_plus',
'at',
'at_circle',
'backward_end_alt_fill',
'backward_end_fill',
'backward_end',
'backward_end_alt',
'backward',
'bag_fill_badge_minus',
'bag_fill',
'bag_badge_minus',
'badge_plus_radiowaves_right',
'bag_fill_badge_plus',
'at_badge_minus',
'bag_badge_plus',
'bag',
'bandage',
'barcode',
'bars',
'bed_double_fill',
'backward_fill',
'battery_0',
'bandage_fill',
'barcode_viewfinder',
'bell_circle_fill',
'bed_double',
'bell_slash_fill',
'bell_circle',
'battery_100',
'battery_25',
'bin_xmark_fill',
'bell_slash',
'bell',
'bin_xmark',
'bitcoin_circle',
'bitcoin',
'bitcoin_circle_fill',
'bold_italic_underline',
'bold',
'bold_underline',
'bolt_circle_fill',
'bolt_badge_a',
'bolt_badge_a_fill',
'bolt_circle',
'bell_fill',
'bolt_fill',
'bolt_horizontal_circle_fill',
'bolt_horizontal_fill',
'book_circle',
'bookmark_fill',
'bolt_horizontal_circle',
'book_fill',
'bolt_horizontal',
'bookmark',
'book_circle_fill',
'bubble_right_fill',
'bubble_left',
'bubble_left_fill',
'briefcase_fill',
'bubble_left_bubble_right',
'bubble_right',
'burn',
'camera',
'building_2_fill',
'bolt',
'book',
'bolt_slash',
'burst_fill',
'camera_circle_fill',
'bubble_left_bubble_right_fill',
'camera_on_rectangle_fill',
'checkmark_rectangle_fill',
'camera_fill',
'bubble_middle_bottom',
'camera_rotate_fill',
'cart_badge_minus',
'camera_on_rectangle',
'bubble_middle_bottom_fill',
'bubble_middle_top_fill',
'camera_viewfinder',
'camera_circle',
'capslock_fill',
'capsule_fill',
'capsule',
'bubble_middle_top',
'capslock',
'calendar',
'car_fill',
'captions_bubble_fill',
'bolt_slash_fill',
'captions_bubble',
'cart_fill',
'cart_fill_badge_minus',
'cart_fill_badge_plus',
'cart_badge_plus',
'cart',
'burst',
'chart_bar_fill',
'chart_bar_square_fill',
'chart_bar',
'chart_bar_square',
'chat_bubble_fill',
'chart_bar_circle',
'cloud_download_fill',
'chat_bubble',
'checkmark_alt_circle_fill',
'chat_bubble_2_fill',
'chat_bubble_text',
'checkmark_shield_fill',
'checkmark_square',
'checkmark_alt_circle',
'chevron_compact_left',
'chevron_down_square_fill',
'checkmark',
'chevron_down_square',
'chevron_compact_down',
'chat_bubble_text_fill',
'calendar_circle_fill',
'calendar_badge_plus',
'checkmark_shield',
'chevron_left_circle_fill',
'chevron_left_circle',
'calendar_badge_minus',
'chevron_down_circle',
'chevron_left_square_fill',
'chevron_left_2',
'chevron_left',
'chevron_left_slash_chevron_right',
'device_phone_portrait',
'chevron_down',
'chevron_right_circle_fill',
'chat_bubble_2',
'chevron_right_square_fill',
'calendar_today',
'chevron_right',
'calendar_circle',
'chevron_up_circle_fill',
'chevron_up_chevron_down',
'chevron_up_circle',
'chevron_left_square',
'chevron_right_square',
'chevron_up_square',
'checkmark_seal',
'chevron_up_square_fill',
'chevron_right_2',
'circle_fill',
'chart_bar_circle_fill',
'chevron_up',
'chart_bar_alt_fill',
'circle_grid_3x3_fill',
'circle_lefthalf_fill',
'circle_righthalf_fill',
'circle',
'circle_grid_hex_fill',
'clock_fill',
'clock',
'clear_fill',
'clear',
'cloud_bolt_fill',
'cloud_bolt_rain',
'chart_pie_fill',
'cloud_bolt_rain_fill',
'cloud_bolt',
'checkmark_square_fill',
'envelope_badge',
'cloud_drizzle_fill',
'cloud_drizzle',
'cloud_fog',
'cloud_heavyrain_fill',
'chart_pie',
'cloud_moon_bolt_fill',
'equal_square_fill',
'checkmark_circle_fill',
'checkmark_circle',
'cloud_heavyrain',
'cloud_hail_fill',
'cloud_hail',
'camera_rotate',
'checkmark_rectangle',
'checkmark_seal_fill',
'cat',
'circle_grid_hex',
'cloud_moon_fill',
'cloud_moon_rain_fill',
'cloud_rain',
'cloud_moon_rain',
'cloud_download',
'circle_grid_3x3',
'cloud_sun_fill',
'chevron_compact_up',
'cloud_moon_bolt',
'chevron_compact_right',
'cloud_rain_fill',
'cloud_sun_bolt_fill',
'color_filter_fill',
'cloud_sun',
'cloud',
'cloud_upload_fill',
'creditcard_fill',
'command',
'control',
'compass',
'creditcard',
'color_filter',
'crop',
'cube_box',
'cloud_sleet',
'cube_fill',
'cloud_sleet_fill',
'cube',
'gift_alt',
'decrease_indent',
'cursor_rays',
'delete_left_fill',
'decrease_quotelevel',
'crop_rotate',
'delete_left',
'cloud_sun_bolt',
'delete_right',
'device_laptop',
'cloud_sun_rain',
'graph_circle',
'cloud_snow_fill',
'delete_right_fill',
'device_desktop',
'cloud_sun_rain_fill',
'device_phone_landscape',
'device_tablet_portrait',
'hand_draw',
'chevron_right_circle',
'hand_raised_fill',
'divide_circle_fill',
'cloud_upload',
'divide_circle',
'divide_square_fill',
'divide',
'dial_fill',
'divide_square',
'doc_chart',
'circle_bottomthird_split',
'doc_checkmark_fill',
'doc_fill',
'cloud_snow',
'doc_append',
'doc_circle',
'doc_circle_fill',
'doc_chart_fill',
'doc_on_doc_fill',
'doc_on_clipboard_fill',
'doc_checkmark',
'doc_on_doc',
'increase_indent',
'doc_person_fill',
'doc_plaintext',
'doc_text_fill',
'doc_text',
'doc',
'doc_richtext',
'dot_square_fill',
'dot_square',
'dot_radiowaves_right',
'download_circle',
'doc_on_clipboard',
'download_circle_fill',
'exclamationmark_square_fill',
'exclamationmark_square',
'eye_fill',
'drop_triangle_fill',
'eye_slash_fill',
'exclamationmark_triangle_fill',
'eyedropper_full',
'eye_slash',
'eyedropper_halffull',
'eye',
'f_cursive_circle',
'eyedropper',
'f_cursive_circle_fill',
'f_cursive',
'flag_fill',
'flag_circle_fill',
'drop_fill',
'flag_circle',
'eyeglasses',
'flag_slash',
'flag_slash_fill',
'flag',
'flame',
'flame_fill',
'floppy_disk',
'flowchart_fill',
'dot_radiowaves_left_right',
'doc_text_viewfinder',
'folder_badge_minus',
'folder_circle_fill',
'folder_badge_person_crop',
'folder_circle',
'lock_rotation_open',
'folder_fill_badge_person_crop',
'folder_fill_badge_minus',
'doc_text_search',
'expand',
'flowchart',
'folder',
'compass_fill',
'folder_fill_badge_plus',
'folder_fill',
'forward_end_alt_fill',
'film',
'forward_end',
'forward_end_fill',
'forward_end_alt',
'forward_fill',
'forward',
'fx',
'gamecontroller_alt_fill',
'gamecontroller_fill',
'dog',
'gear_alt_fill',
'gamecontroller',
'gauge_badge_minus',
'gauge',
'cube_box_fill',
'gift_alt_fill',
'gift_fill',
'gobackward_10',
'gift',
'gobackward_15',
'gobackward_30',
'gobackward_90',
'gobackward_45',
'gobackward_75',
'gobackward_60',
'gobackward_minus',
'function',
'gobackward',
'goforward_30',
'goforward_15',
'goforward_10',
'goforward_45',
'goforward_60',
'goforward_90',
'gauge_badge_plus',
'goforward_plus',
'goforward',
'goforward_75',
'gear_alt',
'desktopcomputer',
'graph_square_fill',
'graph_square',
'graph_circle_fill',
'greaterthan_square',
'grid_circle',
'globe',
'device_tablet_landscape',
'hand_point_left_fill',
'grid_circle_fill',
'gear',
'grid',
'greaterthan',
'hand_point_right_fill',
'hand_point_left',
'dial',
'hand_raised_slash_fill',
'hand_raised',
'hand_thumbsdown_fill',
'hand_raised_slash',
'hand_thumbsdown',
'heart_circle_fill',
'hand_thumbsup_fill',
'hare_fill',
'heart_fill',
'hand_thumbsup',
'heart_circle',
'heart_slash_circle_fill',
'heart_slash_fill',
'heart_slash',
'heart_slash_circle',
'heart',
'hexagon_fill',
'helm',
'hifispeaker',
'hexagon',
'hourglass',
'hourglass_bottomhalf_fill',
'hourglass_tophalf_fill',
'house_alt',
'house',
'guitars',
'person_crop_square_fill',
'info_circle',
'doc_person',
'infinite',
'house_fill',
'info_circle_fill',
'hurricane',
'italic',
'info',
'lasso',
'largecircle_fill_circle',
'hare',
'layers_alt_fill',
'drop_triangle',
'eject_fill',
'ear',
'eject',
'ellipses_bubble_fill',
'ellipsis_circle',
'ellipsis_circle_fill',
'ellipsis_vertical',
'ellipsis_vertical_circle_fill',
'cloud_fill',
'ellipses_bubble',
'ellipsis_vertical_circle',
'envelope_badge_fill',
'cloud_fog_fill',
'ellipsis',
'envelope_circle_fill',
'envelope_open_fill',
'envelope_fill',
'envelope_open',
'envelope',
'equal_circle',
'equal_circle_fill',
'equal',
'envelope_circle',
'checkmark_alt',
'equal_square',
'exclamationmark_bubble_fill',
'exclamationmark_bubble',
'layers_fill',
'escape',
'layers',
'drop',
'lessthan_circle',
'lightbulb_slash_fill',
'lightbulb',
'light_min',
'lessthan',
'lightbulb_fill',
'lessthan_square',
'lessthan_circle_fill',
'light_max',
'lightbulb_slash',
'exclamationmark_triangle',
'line_horizontal_3_decrease_circle_fill',
'line_horizontal_3',
'layers_alt',
'line_horizontal_3_decrease_circle',
'link_circle',
'link_circle_fill',
'line_horizontal_3_decrease',
'link',
'list_bullet_indent',
'list_bullet_below_rectangle',
'list_bullet',
'location_north',
'list_dash',
'location',
'keyboard',
'location_slash_fill',
'location_slash',
'lock_circle_fill',
'lock_circle',
'lock_fill',
'rectangle_fill_on_rectangle_fill',
'folder_badge_plus',
'lock_open_fill',
'lock_open',
'lock_shield_fill',
'lock_shield',
'lock_slash',
'lock_slash_fill',
'lock',
'rectangle_on_rectangle',
'logo_facebook',
'film_fill',
'logo_instagram',
'logo_google',
'logo_googleplus',
'logo_github',
'logo_ios',
'list_number_rtl',
'logo_twitter',
'logo_linkedin',
'logo_windows',
'macwindow',
'list_number',
'map_fill',
'map_pin',
'map_pin_ellipse',
'map',
'memories_badge_minus',
'menu',
'logo_android',
'memories',
'memories_badge_plus',
'logo_google_text',
'minus_circle_fill',
'metronome',
'mic_circle_fill',
'mic_fill',
'mic_circle',
'minus_circle',
'minus_rectangle',
'minus',
'logo_macos',
'money_dollar_circle',
'minus_square',
'money_dollar_circle_fill',
'minus_rectangle_fill',
'mic_slash',
'minus_slash_plus',
'money_dollar',
'money_euro_circle',
'minus_square_fill',
'moon_fill',
'money_euro',
'money_euro_circle_fill',
'mic',
'money_pound_circle_fill',
'moon_zzz_fill',
'moon',
'moon_stars_fill',
'moon_stars',
'moon_zzz',
'multiply_circle_fill',
'multiply_square',
'smallcircle_fill_circle_fill',
'multiply_circle',
'map_pin_slash',
'multiply',
'music_house_fill',
'music_mic',
'music_note_2',
'music_house',
'music_note',
'nosign',
'number_square_fill',
'greaterthan_square_fill',
'greaterthan_circle',
'number_circle_fill',
'multiply_square_fill',
'number',
'hammer',
'option',
'music_albums',
'sort_up',
'number_circle',
'hand_draw_fill',
'pano_fill',
'move',
'logo_android_text',
'paintbrush_fill',
'paintbrush',
'number_square',
'hand_point_right',
'paperclip',
'paperplane',
'pause_rectangle',
'paragraph',
'paperplane_fill',
'pause_fill',
'pause_circle_fill',
'pencil',
'logo_microsoft',
'pencil_ellipsis_rectangle',
'pause_rectangle_fill',
'pencil_slash',
'pencil_circle',
'pause',
'pencil_outline',
'pause_circle',
'person_crop_circle_badge_minus',
'person_crop_circle_fill_badge_checkmark',
'person_crop_circle_fill_badge_minus',
'pencil_circle_fill',
'person_crop_circle_badge_plus',
'person_crop_circle_fill_badge_exclam',
'person_crop_circle_badge_xmark',
'person_crop_rectangle_fill',
'music_note_list',
'person_crop_circle_fill_badge_xmark',
'person_fill',
'person_crop_circle_fill',
'person',
'person_crop_rectangle',
'person_crop_circle',
'person_crop_circle_fill_badge_plus',
'perspective',
'personalhotspot',
'increase_quotelevel',
'house_alt_fill',
'phone_arrow_down_left',
'person_crop_square',
'phone_arrow_up_right',
'square_stack',
'phone_arrow_right',
'phone_circle',
'phone_down_circle_fill',
'phone_down_circle',
'square_stack_3d_down_right_fill',
'photo_fill_on_rectangle_fill',
'phone',
'photo_on_rectangle',
'photo',
'phone_down',
'phone_fill_arrow_right',
'photo_fill',
'phone_fill_arrow_down_left',
'pano',
'piano',
'placemark_fill',
'pin',
'pin_fill',
'pin_slash_fill',
'pin_slash',
'placemark',
'play_fill',
'play_circle_fill',
'phone_badge_plus',
'play_rectangle',
'exclamationmark_circle',
'playpause_fill',
'exclamationmark_octagon_fill',
'play_circle',
'exclamationmark_circle_fill',
'exclamationmark_shield_fill',
'paw',
'exclamationmark_shield',
'exclamationmark',
'playpause',
'cloud_moon',
'lessthan_square_fill',
'plus_app',
'keyboard_chevron_compact_down',
'play_rectangle_fill',
'plus_bubble',
'plus_rectangle_fill',
'plus_circle_fill',
'plus_rectangle_fill_on_rectangle_fill',
'plus_circle',
'plus_rectangle',
'plus',
'plus_square_fill',
'plus_rectangle_on_rectangle',
'plus_slash_minus',
'plus_square_on_square',
'plusminus',
'plusminus_circle',
'plus_square_fill_on_square_fill',
'poultry_leg',
'printer',
'printer_fill',
'plus_bubble_fill',
'plusminus_circle_fill',
'power',
'question_circle_fill',
'sun_dust_fill',
'purchased_circle_fill',
'purchased',
'question_circle',
'question_diamond_fill',
'question_diamond',
'play',
'question_square',
'purchased_circle',
'question',
'question_square_fill',
'radiowaves_left',
'location_north_line_fill',
'quote_bubble_fill',
'location_fill',
'location_circle_fill',
'quote_bubble',
'location_circle',
'recordingtape',
'location_north_fill',
'rectangle_3_offgrid_fill',
'rectangle_arrow_up_right_arrow_down_left_slash',
'rectangle_3_offgrid',
'rays',
'rectangle_arrow_up_right_arrow_down_left',
'plus_app_fill',
'leaf_arrow_circlepath',
'qrcode',
'rectangle_fill_on_rectangle_angled_fill',
'rectangle_badge_checkmark',
'plus_square',
'radiowaves_right',
'qrcode_viewfinder',
'rectangle_fill_badge_checkmark',
'lock_rotation',
'rectangle_fill_badge_xmark',
'rectangle_expand_vertical',
'rectangle_grid_2x2_fill',
'rectangle_badge_xmark',
'rectangle_compress_vertical',
'rectangle_fill',
'rectangle_grid_1x2_fill',
'location_north_line',
'rectangle_grid_1x2',
'rectangle_grid_3x2_fill',
'rectangle_dock',
'logo_apple',
'rectangle_grid_2x2',
'rectangle_on_rectangle_angled',
'rectangle_stack_badge_minus',
'rectangle_split_3x1_fill',
'rectangle_split_3x3_fill',
'rectangle_stack_badge_person_crop',
'rectangle_split_3x3',
'rectangle_paperclip',
'rectangle_stack_badge_plus',
'rectangle_stack_fill_badge_person_crop',
'logo_rss',
'rectangle_stack_fill',
'rectangle_stack_fill_badge_minus',
'rectangle',
'rectangle_split_3x1',
'rectangle_stack',
'rectangle_stack_fill_badge_plus',
'rectangle_stack_person_crop',
'rectangle_stack_person_crop_fill',
'repeat',
'resize_h',
'resize_v',
'repeat_1',
'resize',
'return_',
'rectangle_grid_3x2',
'rosette',
'rocket_fill',
'mic_slash_fill',
'rotate_left_fill',
'scissors_alt',
'rhombus',
'search',
'rotate_left',
'selection_pin_in_out',
'rotate_right',
'shield_fill',
'scissors',
'rotate_right_fill',
'shield_slash_fill',
'money_pound',
'money_pound_circle',
'rhombus_fill',
'shield_slash',
'scope',
'money_yen_circle_fill',
'money_rubl_circle',
'money_rubl',
'waveform_path_badge_minus',
'money_yen_circle',
'moon_circle',
'money_yen',
'shift_fill',
'moon_circle_fill',
'shield',
'rocket',
'shift',
'sidebar_right',
'sidebar_left',
'shuffle',
'skew',
'slash_circle',
'wand_stars_inverse',
'slash_circle_fill',
'slider_horizontal_below_rectangle',
'smallcircle_circle_fill',
'slider_horizontal_3',
'music_albums_fill',
'smallcircle_circle',
'smiley',
'smiley_fill',
'smallcircle_fill_circle',
'greaterthan_circle_fill',
'smoke_fill',
'sort_down_circle_fill',
'smoke',
'sort_down',
'sort_down_circle',
'sort_up_circle_fill',
'sort_up_circle',
'hammer_fill',
'signature',
'sparkles',
'speaker_1_fill',
'speaker_1',
'speaker_2',
'speaker_2_fill',
'speaker_fill',
'slowmo',
'speaker_3_fill',
'speaker_slash_fill_rtl',
'speaker_slash_fill',
'speaker_3',
'speaker_slash',
'speaker_slash_rtl',
'speaker_zzz_fill',
'sportscourt_fill',
'speaker',
'snow',
'sportscourt',
'square_arrow_down_on_square_fill',
'square_arrow_down_fill',
'speaker_zzz_rtl',
'sun_haze',
'sun_haze_fill',
'suit_heart',
'speaker_zzz',
'star_circle_fill',
'sun_min',
'text_cursor',
'text_alignright',
'triangle_fill',
'phone_fill_badge_plus',
'text_justify',
'tray_arrow_up_fill',
'tray_arrow_down',
'textbox',
'triangle',
'text_badge_plus',
'person_2_square_stack_fill',
'square_stack_3d_up',
'tray_full',
'search_circle',
'person_circle',
'videocam_circle_fill',
'zzz',
'trash_slash',
'person_badge_plus_fill',
'square_arrow_up_on_square',
'umbrella',
'square_favorites_alt',
'xmark_square',
'wand_rays',
'wind',
'square_arrow_down_on_square',
'waveform_path_badge_plus',
'person_2_square_stack',
'waveform',
'hifispeaker_fill',
'square_arrow_up_on_square_fill',
'square_arrow_left',
'viewfinder_circle',
'viewfinder_circle_fill',
'xmark_octagon_fill',
'xmark_shield_fill',
'videocam_fill',
'phone_fill_arrow_up_right',
'stop',
'shield_lefthalf_fill',
'person_badge_plus',
'person_2',
'square_arrow_up',
'tv',
'scribble',
'uiwindow_split_2x1',
'viewfinder',
'zoom_out',
'tv_music_note_fill',
'square_arrow_up_fill',
'view_2d',
'speedometer',
'square_fill_line_vertical_square_fill',
'star_lefthalf_fill',
'square_grid_2x2_fill',
'suit_heart_fill',
'square_fill',
'square_arrow_left_fill',
'star_fill',
'wrench_fill',
'staroflife',
'staroflife_fill',
'square',
'square_fill_on_square_fill',
'star_slash',
'sun_max',
'sun_max_fill',
'star',
'text_aligncenter',
'suit_club',
'timer',
'triangle_lefthalf_fill',
'text_justifyleft',
'textformat_alt',
'today_fill',
'trash_circle',
'text_badge_minus',
'star_slash_fill',
'tropicalstorm',
'square_stack_3d_up_slash',
'table_badge_more_fill',
'trash',
'textformat_abc',
'table',
'textformat',
'tray_2_fill',
'xmark_seal',
'text_bubble_fill',
'xmark_square_fill',
'person_2_alt',
'tree',
'thermometer_sun',
'tortoise',
'strikethrough',
'textformat_abc_dottedunderline',
'trash_slash_fill',
'textformat_123',
'sun_dust',
'phone_down_fill',
'tray',
'exclamationmark_octagon',
'text_badge_xmark',
'timer_fill',
'tornado',
'text_insert',
'textformat_superscript',
'tag_circle',
'phone_fill',
'suit_club_fill',
'ticket',
'textformat_size',
'sun_min_fill',
'sum',
'person_badge_minus_fill',
'tray_arrow_down_fill',
'waveform_path_ecg',
'tv_circle_fill',
'tuningfork',
'xmark_shield',
'xmark_rectangle_fill',
'waveform_circle',
'square_split_2x1',
'person_crop_circle_badge_checkmark',
'upload_circle',
'wand_rays_inverse',
'person_badge_minus',
'zoom_in',
'wifi_exclamationmark',
'headphones',
'xmark_circle_fill',
'xmark_seal_fill',
'suit_spade',
'upload_circle_fill',
'square_grid_3x2',
'money_rubl_circle_fill',
'videocam_circle',
'tag_circle_fill',
'textformat_subscript',
'tortoise_fill',
'table_fill',
'stop_circle_fill',
'text_justifyright',
'text_alignleft',
'square_favorites',
'projective',
'trash_circle_fill',
'today',
'tickets_fill',
'tram_fill',
'stop_fill',
'triangle_righthalf_fill',
'tray_full_fill',
'tag_fill',
'tray_fill',
'text_quote',
'tray_2',
'text_badge_checkmark',
'text_append',
'stopwatch_fill',
't_bubble',
'square_fill_on_circle_fill',
'person_crop_circle_badge_exclam',
'sunset_fill',
'sunrise',
'suit_diamond_fill',
'sunset',
't_bubble_fill',
'square_righthalf_fill',
'square_lefthalf_fill',
'square_line_vertical_square_fill',
'tray_arrow_up',
'square_split_1x2',
'square_pencil',
'square_on_square',
'square_grid_2x2',
'square_line_vertical_square',
'square_list_fill',
'square_stack_3d_down_right',
'phone_circle_fill',
'thermometer_snowflake',
'square_stack_3d_up_fill',
'square_split_2x2',
'square_split_2x2_fill',
'square_stack_fill',
'suit_spade_fill',
'percent',
'xmark_octagon',
'wrench',
'xmark',
'search_circle_fill',
'tv_fill',
'tv_circle',
'waveform_path',
'square_fill_line_vertical_square',
'underline',
'person_circle_fill',
'square_favorites_alt_fill',
'square_grid_4x3_fill',
'square_stack_3d_down_dottedline',
'square_arrow_right_fill',
'square_split_1x2_fill',
'tv_music_note',
'suit_diamond',
'star_circle',
'squares_below_rectangle',
'wifi',
'timelapse',
'waveform_circle_fill',
'sunrise_fill',
'wind_snow',
'table_badge_more',
'stop_circle',
'text_bubble',
'ticket_fill',
'square_grid_3x2_fill',
'thermometer',
'stopwatch',
'person_alt',
'square_on_circle',
'square_pencil_fill',
'square_list',
'person_3',
'speaker_zzz_fill_rtl',
'videocam',
'person_3_fill',
'wifi_slash',
'xmark_circle',
'square_arrow_right',
'person_2_fill',
'xmark_rectangle',
'square_stack_3d_up_slash_fill',
'umbrella_fill',
'square_split_2x1_fill',
'trash_fill',
'square_favorites_fill',
'square_arrow_down',
'view_3d',
'person_alt_circle_fill',
'text_badge_star',
'tickets',
'person_alt_circle',
'wand_stars',
'tag',
'airplane',
];

final Map<String, IconData> iconMap = {
'alarm_fill': SFSymbols.alarm_fill,
'alt': SFSymbols.alt,
'ant_circle_fill': SFSymbols.ant_circle_fill,
'alarm': SFSymbols.alarm,
'ant': SFSymbols.ant,
'app_badge_fill': SFSymbols.app_badge_fill,
'ant_circle': SFSymbols.ant_circle,
'ant_fill': SFSymbols.ant_fill,
'antenna_radiowaves_left_right': SFSymbols.antenna_radiowaves_left_right,
'archivebox_fill': SFSymbols.archivebox_fill,
'app_fill': SFSymbols.app_fill,
'app_badge': SFSymbols.app_badge,
'arrow_2_circlepath_circle': SFSymbols.arrow_2_circlepath_circle,
'app': SFSymbols.app,
'arrow_2_circlepath_circle_fill': SFSymbols.arrow_2_circlepath_circle_fill,
'archivebox': SFSymbols.archivebox,
'arrow_2_circlepath': SFSymbols.arrow_2_circlepath,
'arrow_3_trianglepath': SFSymbols.arrow_3_trianglepath,
'arrow_clockwise_circle': SFSymbols.arrow_clockwise_circle,
'arrow_branch': SFSymbols.arrow_branch,
'arrow_2_squarepath': SFSymbols.arrow_2_squarepath,
'arrow_clockwise_circle_fill': SFSymbols.arrow_clockwise_circle_fill,
'arrow_clockwise': SFSymbols.arrow_clockwise,
'arrow_counterclockwise_circle': SFSymbols.arrow_counterclockwise_circle,
'arrow_counterclockwise_circle_fill': SFSymbols.arrow_counterclockwise_circle_fill,
'arrow_down_circle': SFSymbols.arrow_down_circle,
'arrow_counterclockwise': SFSymbols.arrow_counterclockwise,
'arrow_down_circle_fill': SFSymbols.arrow_down_circle_fill,
'arrow_down_left_circle_fill': SFSymbols.arrow_down_left_circle_fill,
'arrow_down_doc_fill': SFSymbols.arrow_down_doc_fill,
'arrow_down_doc': SFSymbols.arrow_down_doc,
'arrow_down_left_square': SFSymbols.arrow_down_left_square,
'arrow_down_right_circle_fill': SFSymbols.arrow_down_right_circle_fill,
'arrow_down_left': SFSymbols.arrow_down_left,
'arrow_down_left_circle': SFSymbols.arrow_down_left_circle,
'arrow_down_left_square_fill': SFSymbols.arrow_down_left_square_fill,
'arrow_down_right_circle': SFSymbols.arrow_down_right_circle,
'arrow_down_right_square_fill': SFSymbols.arrow_down_right_square_fill,
'arrow_down_right_arrow_up_left': SFSymbols.arrow_down_right_arrow_up_left,
'arrow_down_right_square': SFSymbols.arrow_down_right_square,
'arrow_down_square': SFSymbols.arrow_down_square,
'arrow_down_right': SFSymbols.arrow_down_right,
'arrow_down': SFSymbols.arrow_down,
'arrow_down_square_fill': SFSymbols.arrow_down_square_fill,
'arrow_down_to_line': SFSymbols.arrow_down_to_line,
'arrow_left_circle_fill': SFSymbols.arrow_left_circle_fill,
'arrow_left_right_circle_fill': SFSymbols.arrow_left_right_circle_fill,
'arrow_left_circle': SFSymbols.arrow_left_circle,
'arrow_left_right_square': SFSymbols.arrow_left_right_square,
'arrow_down_to_line_alt': SFSymbols.arrow_down_to_line_alt,
'arrow_left_right_square_fill': SFSymbols.arrow_left_right_square_fill,
'arrow_left_right_circle': SFSymbols.arrow_left_right_circle,
'arrow_left_right': SFSymbols.arrow_left_right,
'arrow_left': SFSymbols.arrow_left,
'arrow_left_square_fill': SFSymbols.arrow_left_square_fill,
'arrow_left_to_line_alt': SFSymbols.arrow_left_to_line_alt,
'arrow_right_arrow_left_circle': SFSymbols.arrow_right_arrow_left_circle,
'arrow_merge': SFSymbols.arrow_merge,
'arrow_left_to_line': SFSymbols.arrow_left_to_line,
'arrow_right_arrow_left_circle_fill': SFSymbols.arrow_right_arrow_left_circle_fill,
'arrow_left_square': SFSymbols.arrow_left_square,
'arrow_right_arrow_left_square_fill': SFSymbols.arrow_right_arrow_left_square_fill,
'arrow_right_arrow_left': SFSymbols.arrow_right_arrow_left,
'arrow_right_square_fill': SFSymbols.arrow_right_square_fill,
'arrow_right_circle': SFSymbols.arrow_right_circle,
'arrow_right_circle_fill': SFSymbols.arrow_right_circle_fill,
'arrow_right_arrow_left_square': SFSymbols.arrow_right_arrow_left_square,
'arrow_right_to_line': SFSymbols.arrow_right_to_line,
'arrow_turn_down_left': SFSymbols.arrow_turn_down_left,
'arrow_right_to_line_alt': SFSymbols.arrow_right_to_line_alt,
'arrow_turn_left_up': SFSymbols.arrow_turn_left_up,
'arrow_swap': SFSymbols.arrow_swap,
'arrow_right': SFSymbols.arrow_right,
'arrow_right_square': SFSymbols.arrow_right_square,
'arrow_turn_left_down': SFSymbols.arrow_turn_left_down,
'arrow_turn_right_down': SFSymbols.arrow_turn_right_down,
'arrow_turn_up_left': SFSymbols.arrow_turn_up_left,
'arrow_turn_right_up': SFSymbols.arrow_turn_right_up,
'arrow_turn_up_right': SFSymbols.arrow_turn_up_right,
'arrow_up_arrow_down_circle': SFSymbols.arrow_up_arrow_down_circle,
'arrow_up_arrow_down_circle_fill': SFSymbols.arrow_up_arrow_down_circle_fill,
'arrow_up_arrow_down_square_fill': SFSymbols.arrow_up_arrow_down_square_fill,
'arrow_up_bin_fill': SFSymbols.arrow_up_bin_fill,
'arrow_up_arrow_down_square': SFSymbols.arrow_up_arrow_down_square,
'arrow_up_bin': SFSymbols.arrow_up_bin,
'arrow_up_circle': SFSymbols.arrow_up_circle,
'arrow_turn_down_right': SFSymbols.arrow_turn_down_right,
'arrow_up_doc_fill': SFSymbols.arrow_up_doc_fill,
'arrow_up_doc': SFSymbols.arrow_up_doc,
'arrow_up_arrow_down': SFSymbols.arrow_up_arrow_down,
'arrow_up_down_square_fill': SFSymbols.arrow_up_down_square_fill,
'arrow_up_down_circle_fill': SFSymbols.arrow_up_down_circle_fill,
'arrow_up_down_circle': SFSymbols.arrow_up_down_circle,
'arrow_up_down': SFSymbols.arrow_up_down,
'arrow_up_left_arrow_down_right': SFSymbols.arrow_up_left_arrow_down_right,
'arrow_up_circle_fill': SFSymbols.arrow_up_circle_fill,
'arrow_up_down_square': SFSymbols.arrow_up_down_square,
'arrow_up_left_circle_fill': SFSymbols.arrow_up_left_circle_fill,
'arrow_up_left_square_fill': SFSymbols.arrow_up_left_square_fill,
'arrow_up_right_circle_fill': SFSymbols.arrow_up_right_circle_fill,
'arrow_up_left_circle': SFSymbols.arrow_up_left_circle,
'arrow_up_left_square': SFSymbols.arrow_up_left_square,
'arrow_up_right_diamond_fill': SFSymbols.arrow_up_right_diamond_fill,
'arrow_up_left': SFSymbols.arrow_up_left,
'arrow_up_right_circle': SFSymbols.arrow_up_right_circle,
'arrow_up_right_diamond': SFSymbols.arrow_up_right_diamond,
'arrow_up_right': SFSymbols.arrow_up_right,
'arrow_up_right_square_fill': SFSymbols.arrow_up_right_square_fill,
'arrow_up_square_fill': SFSymbols.arrow_up_square_fill,
'arrow_up_to_line_alt': SFSymbols.arrow_up_to_line_alt,
'arrow_up_to_line': SFSymbols.arrow_up_to_line,
'arrow_up_square': SFSymbols.arrow_up_square,
'arrow_up_right_square': SFSymbols.arrow_up_right_square,
'arrow_up': SFSymbols.arrow_up,
'arrow_uturn_down_circle_fill': SFSymbols.arrow_uturn_down_circle_fill,
'arrow_uturn_down_square': SFSymbols.arrow_uturn_down_square,
'arrow_uturn_left_circle': SFSymbols.arrow_uturn_left_circle,
'arrow_uturn_down_square_fill': SFSymbols.arrow_uturn_down_square_fill,
'arrow_uturn_down': SFSymbols.arrow_uturn_down,
'arrow_uturn_down_circle': SFSymbols.arrow_uturn_down_circle,
'arrow_uturn_left_circle_fill': SFSymbols.arrow_uturn_left_circle_fill,
'arrow_uturn_left': SFSymbols.arrow_uturn_left,
'arrow_uturn_left_square_fill': SFSymbols.arrow_uturn_left_square_fill,
'arrow_uturn_left_square': SFSymbols.arrow_uturn_left_square,
'arrow_uturn_right_circle': SFSymbols.arrow_uturn_right_circle,
'arrow_uturn_right_square_fill': SFSymbols.arrow_uturn_right_square_fill,
'arrow_uturn_right_circle_fill': SFSymbols.arrow_uturn_right_circle_fill,
'arrow_uturn_up_circle_fill': SFSymbols.arrow_uturn_up_circle_fill,
'arrow_uturn_right': SFSymbols.arrow_uturn_right,
'arrow_uturn_right_square': SFSymbols.arrow_uturn_right_square,
'arrow_uturn_up_square': SFSymbols.arrow_uturn_up_square,
'arrow_uturn_up_square_fill': SFSymbols.arrow_uturn_up_square_fill,
'arrow_uturn_up_circle': SFSymbols.arrow_uturn_up_circle,
'arrowshape_turn_up_left_2_fill': SFSymbols.arrowshape_turn_up_left_2_fill,
'arrowshape_turn_up_left_circle_fill': SFSymbols.arrowshape_turn_up_left_circle_fill,
'arrow_uturn_up': SFSymbols.arrow_uturn_up,
'arrowshape_turn_up_left_2': SFSymbols.arrowshape_turn_up_left_2,
'arrowshape_turn_up_left_fill': SFSymbols.arrowshape_turn_up_left_fill,
'arrowshape_turn_up_left': SFSymbols.arrowshape_turn_up_left,
'arrowshape_turn_up_left_circle': SFSymbols.arrowshape_turn_up_left_circle,
'arrowshape_turn_up_right_circle_fill': SFSymbols.arrowshape_turn_up_right_circle_fill,
'arrowshape_turn_up_right': SFSymbols.arrowshape_turn_up_right,
'arrowtriangle_down_circle_fill': SFSymbols.arrowtriangle_down_circle_fill,
'arrowtriangle_down_square_fill': SFSymbols.arrowtriangle_down_square_fill,
'arrowtriangle_down_fill': SFSymbols.arrowtriangle_down_fill,
'arrowshape_turn_up_right_circle': SFSymbols.arrowshape_turn_up_right_circle,
'arrowtriangle_down_circle': SFSymbols.arrowtriangle_down_circle,
'arrowtriangle_down': SFSymbols.arrowtriangle_down,
'arrowtriangle_left_circle_fill': SFSymbols.arrowtriangle_left_circle_fill,
'arrowshape_turn_up_right_fill': SFSymbols.arrowshape_turn_up_right_fill,
'arrowtriangle_left_fill': SFSymbols.arrowtriangle_left_fill,
'arrowtriangle_left_square_fill': SFSymbols.arrowtriangle_left_square_fill,
'arrowtriangle_right_circle_fill': SFSymbols.arrowtriangle_right_circle_fill,
'arrowtriangle_left': SFSymbols.arrowtriangle_left,
'arrowtriangle_right_square_fill': SFSymbols.arrowtriangle_right_square_fill,
'arrowtriangle_down_square': SFSymbols.arrowtriangle_down_square,
'arrowtriangle_left_square': SFSymbols.arrowtriangle_left_square,
'arrowtriangle_right_fill': SFSymbols.arrowtriangle_right_fill,
'arrowtriangle_left_circle': SFSymbols.arrowtriangle_left_circle,
'arrowtriangle_right_circle': SFSymbols.arrowtriangle_right_circle,
'arrowtriangle_up_fill': SFSymbols.arrowtriangle_up_fill,
'arrowtriangle_right_square': SFSymbols.arrowtriangle_right_square,
'arrowtriangle_up_circle': SFSymbols.arrowtriangle_up_circle,
'arrowtriangle_right': SFSymbols.arrowtriangle_right,
'arrowtriangle_up_circle_fill': SFSymbols.arrowtriangle_up_circle_fill,
'arrowtriangle_up_square_fill': SFSymbols.arrowtriangle_up_square_fill,
'arrowtriangle_up': SFSymbols.arrowtriangle_up,
'arrowtriangle_up_square': SFSymbols.arrowtriangle_up_square,
'asterisk_circle_fill': SFSymbols.asterisk_circle_fill,
'asterisk_circle': SFSymbols.asterisk_circle,
'at_circle_fill': SFSymbols.at_circle_fill,
'at_badge_plus': SFSymbols.at_badge_plus,
'at': SFSymbols.at,
'at_circle': SFSymbols.at_circle,
'backward_end_alt_fill': SFSymbols.backward_end_alt_fill,
'backward_end_fill': SFSymbols.backward_end_fill,
'backward_end': SFSymbols.backward_end,
'backward_end_alt': SFSymbols.backward_end_alt,
'backward': SFSymbols.backward,
'bag_fill_badge_minus': SFSymbols.bag_fill_badge_minus,
'bag_fill': SFSymbols.bag_fill,
'bag_badge_minus': SFSymbols.bag_badge_minus,
'badge_plus_radiowaves_right': SFSymbols.badge_plus_radiowaves_right,
'bag_fill_badge_plus': SFSymbols.bag_fill_badge_plus,
'at_badge_minus': SFSymbols.at_badge_minus,
'bag_badge_plus': SFSymbols.bag_badge_plus,
'bag': SFSymbols.bag,
'bandage': SFSymbols.bandage,
'barcode': SFSymbols.barcode,
'bars': SFSymbols.bars,
'bed_double_fill': SFSymbols.bed_double_fill,
'backward_fill': SFSymbols.backward_fill,
'battery_0': SFSymbols.battery_0,
'bandage_fill': SFSymbols.bandage_fill,
'barcode_viewfinder': SFSymbols.barcode_viewfinder,
'bell_circle_fill': SFSymbols.bell_circle_fill,
'bed_double': SFSymbols.bed_double,
'bell_slash_fill': SFSymbols.bell_slash_fill,
'bell_circle': SFSymbols.bell_circle,
'battery_100': SFSymbols.battery_100,
'battery_25': SFSymbols.battery_25,
'bin_xmark_fill': SFSymbols.bin_xmark_fill,
'bell_slash': SFSymbols.bell_slash,
'bell': SFSymbols.bell,
'bin_xmark': SFSymbols.bin_xmark,
'bitcoin_circle': SFSymbols.bitcoin_circle,
'bitcoin': SFSymbols.bitcoin,
'bitcoin_circle_fill': SFSymbols.bitcoin_circle_fill,
'bold_italic_underline': SFSymbols.bold_italic_underline,
'bold': SFSymbols.bold,
'bold_underline': SFSymbols.bold_underline,
'bolt_circle_fill': SFSymbols.bolt_circle_fill,
'bolt_badge_a': SFSymbols.bolt_badge_a,
'bolt_badge_a_fill': SFSymbols.bolt_badge_a_fill,
'bolt_circle': SFSymbols.bolt_circle,
'bell_fill': SFSymbols.bell_fill,
'bolt_fill': SFSymbols.bolt_fill,
'bolt_horizontal_circle_fill': SFSymbols.bolt_horizontal_circle_fill,
'bolt_horizontal_fill': SFSymbols.bolt_horizontal_fill,
'book_circle': SFSymbols.book_circle,
'bookmark_fill': SFSymbols.bookmark_fill,
'bolt_horizontal_circle': SFSymbols.bolt_horizontal_circle,
'book_fill': SFSymbols.book_fill,
'bolt_horizontal': SFSymbols.bolt_horizontal,
'bookmark': SFSymbols.bookmark,
'book_circle_fill': SFSymbols.book_circle_fill,
'bubble_right_fill': SFSymbols.bubble_right_fill,
'bubble_left': SFSymbols.bubble_left,
'bubble_left_fill': SFSymbols.bubble_left_fill,
'briefcase_fill': SFSymbols.briefcase_fill,
'bubble_left_bubble_right': SFSymbols.bubble_left_bubble_right,
'bubble_right': SFSymbols.bubble_right,
'burn': SFSymbols.burn,
'camera': SFSymbols.camera,
'building_2_fill': SFSymbols.building_2_fill,
'bolt': SFSymbols.bolt,
'book': SFSymbols.book,
'bolt_slash': SFSymbols.bolt_slash,
'burst_fill': SFSymbols.burst_fill,
'camera_circle_fill': SFSymbols.camera_circle_fill,
'bubble_left_bubble_right_fill': SFSymbols.bubble_left_bubble_right_fill,
'camera_on_rectangle_fill': SFSymbols.camera_on_rectangle_fill,
'checkmark_rectangle_fill': SFSymbols.checkmark_rectangle_fill,
'camera_fill': SFSymbols.camera_fill,
'bubble_middle_bottom': SFSymbols.bubble_middle_bottom,
'camera_rotate_fill': SFSymbols.camera_rotate_fill,
'cart_badge_minus': SFSymbols.cart_badge_minus,
'camera_on_rectangle': SFSymbols.camera_on_rectangle,
'bubble_middle_bottom_fill': SFSymbols.bubble_middle_bottom_fill,
'bubble_middle_top_fill': SFSymbols.bubble_middle_top_fill,
'camera_viewfinder': SFSymbols.camera_viewfinder,
'camera_circle': SFSymbols.camera_circle,
'capslock_fill': SFSymbols.capslock_fill,
'capsule_fill': SFSymbols.capsule_fill,
'capsule': SFSymbols.capsule,
'bubble_middle_top': SFSymbols.bubble_middle_top,
'capslock': SFSymbols.capslock,
'calendar': SFSymbols.calendar,
'car_fill': SFSymbols.car_fill,
'captions_bubble_fill': SFSymbols.captions_bubble_fill,
'bolt_slash_fill': SFSymbols.bolt_slash_fill,
'captions_bubble': SFSymbols.captions_bubble,
'cart_fill': SFSymbols.cart_fill,
'cart_fill_badge_minus': SFSymbols.cart_fill_badge_minus,
'cart_fill_badge_plus': SFSymbols.cart_fill_badge_plus,
'cart_badge_plus': SFSymbols.cart_badge_plus,
'cart': SFSymbols.cart,
'burst': SFSymbols.burst,
'chart_bar_fill': SFSymbols.chart_bar_fill,
'chart_bar_square_fill': SFSymbols.chart_bar_square_fill,
'chart_bar': SFSymbols.chart_bar,
'chart_bar_square': SFSymbols.chart_bar_square,
'chat_bubble_fill': SFSymbols.chat_bubble_fill,
'chart_bar_circle': SFSymbols.chart_bar_circle,
'cloud_download_fill': SFSymbols.cloud_download_fill,
'chat_bubble': SFSymbols.chat_bubble,
'checkmark_alt_circle_fill': SFSymbols.checkmark_alt_circle_fill,
'chat_bubble_2_fill': SFSymbols.chat_bubble_2_fill,
'chat_bubble_text': SFSymbols.chat_bubble_text,
'checkmark_shield_fill': SFSymbols.checkmark_shield_fill,
'checkmark_square': SFSymbols.checkmark_square,
'checkmark_alt_circle': SFSymbols.checkmark_alt_circle,
'chevron_compact_left': SFSymbols.chevron_compact_left,
'chevron_down_square_fill': SFSymbols.chevron_down_square_fill,
'checkmark': SFSymbols.checkmark,
'chevron_down_square': SFSymbols.chevron_down_square,
'chevron_compact_down': SFSymbols.chevron_compact_down,
'chat_bubble_text_fill': SFSymbols.chat_bubble_text_fill,
'calendar_circle_fill': SFSymbols.calendar_circle_fill,
'calendar_badge_plus': SFSymbols.calendar_badge_plus,
'checkmark_shield': SFSymbols.checkmark_shield,
'chevron_left_circle_fill': SFSymbols.chevron_left_circle_fill,
'chevron_left_circle': SFSymbols.chevron_left_circle,
'calendar_badge_minus': SFSymbols.calendar_badge_minus,
'chevron_down_circle': SFSymbols.chevron_down_circle,
'chevron_left_square_fill': SFSymbols.chevron_left_square_fill,
'chevron_left_2': SFSymbols.chevron_left_2,
'chevron_left': SFSymbols.chevron_left,
'chevron_left_slash_chevron_right': SFSymbols.chevron_left_slash_chevron_right,
'device_phone_portrait': SFSymbols.device_phone_portrait,
'chevron_down': SFSymbols.chevron_down,
'chevron_right_circle_fill': SFSymbols.chevron_right_circle_fill,
'chat_bubble_2': SFSymbols.chat_bubble_2,
'chevron_right_square_fill': SFSymbols.chevron_right_square_fill,
'calendar_today': SFSymbols.calendar_today,
'chevron_right': SFSymbols.chevron_right,
'calendar_circle': SFSymbols.calendar_circle,
'chevron_up_circle_fill': SFSymbols.chevron_up_circle_fill,
'chevron_up_chevron_down': SFSymbols.chevron_up_chevron_down,
'chevron_up_circle': SFSymbols.chevron_up_circle,
'chevron_left_square': SFSymbols.chevron_left_square,
'chevron_right_square': SFSymbols.chevron_right_square,
'chevron_up_square': SFSymbols.chevron_up_square,
'checkmark_seal': SFSymbols.checkmark_seal,
'chevron_up_square_fill': SFSymbols.chevron_up_square_fill,
'chevron_right_2': SFSymbols.chevron_right_2,
'circle_fill': SFSymbols.circle_fill,
'chart_bar_circle_fill': SFSymbols.chart_bar_circle_fill,
'chevron_up': SFSymbols.chevron_up,
'chart_bar_alt_fill': SFSymbols.chart_bar_alt_fill,
'circle_grid_3x3_fill': SFSymbols.circle_grid_3x3_fill,
'circle_lefthalf_fill': SFSymbols.circle_lefthalf_fill,
'circle_righthalf_fill': SFSymbols.circle_righthalf_fill,
'circle': SFSymbols.circle,
'circle_grid_hex_fill': SFSymbols.circle_grid_hex_fill,
'clock_fill': SFSymbols.clock_fill,
'clock': SFSymbols.clock,
'clear_fill': SFSymbols.clear_fill,
'clear': SFSymbols.clear,
'cloud_bolt_fill': SFSymbols.cloud_bolt_fill,
'cloud_bolt_rain': SFSymbols.cloud_bolt_rain,
'chart_pie_fill': SFSymbols.chart_pie_fill,
'cloud_bolt_rain_fill': SFSymbols.cloud_bolt_rain_fill,
'cloud_bolt': SFSymbols.cloud_bolt,
'checkmark_square_fill': SFSymbols.checkmark_square_fill,
'envelope_badge': SFSymbols.envelope_badge,
'cloud_drizzle_fill': SFSymbols.cloud_drizzle_fill,
'cloud_drizzle': SFSymbols.cloud_drizzle,
'cloud_fog': SFSymbols.cloud_fog,
'cloud_heavyrain_fill': SFSymbols.cloud_heavyrain_fill,
'chart_pie': SFSymbols.chart_pie,
'cloud_moon_bolt_fill': SFSymbols.cloud_moon_bolt_fill,
'equal_square_fill': SFSymbols.equal_square_fill,
'checkmark_circle_fill': SFSymbols.checkmark_circle_fill,
'checkmark_circle': SFSymbols.checkmark_circle,
'cloud_heavyrain': SFSymbols.cloud_heavyrain,
'cloud_hail_fill': SFSymbols.cloud_hail_fill,
'cloud_hail': SFSymbols.cloud_hail,
'camera_rotate': SFSymbols.camera_rotate,
'checkmark_rectangle': SFSymbols.checkmark_rectangle,
'checkmark_seal_fill': SFSymbols.checkmark_seal_fill,
'cat': SFSymbols.cat,
'circle_grid_hex': SFSymbols.circle_grid_hex,
'cloud_moon_fill': SFSymbols.cloud_moon_fill,
'cloud_moon_rain_fill': SFSymbols.cloud_moon_rain_fill,
'cloud_rain': SFSymbols.cloud_rain,
'cloud_moon_rain': SFSymbols.cloud_moon_rain,
'cloud_download': SFSymbols.cloud_download,
'circle_grid_3x3': SFSymbols.circle_grid_3x3,
'cloud_sun_fill': SFSymbols.cloud_sun_fill,
'chevron_compact_up': SFSymbols.chevron_compact_up,
'cloud_moon_bolt': SFSymbols.cloud_moon_bolt,
'chevron_compact_right': SFSymbols.chevron_compact_right,
'cloud_rain_fill': SFSymbols.cloud_rain_fill,
'cloud_sun_bolt_fill': SFSymbols.cloud_sun_bolt_fill,
'color_filter_fill': SFSymbols.color_filter_fill,
'cloud_sun': SFSymbols.cloud_sun,
'cloud': SFSymbols.cloud,
'cloud_upload_fill': SFSymbols.cloud_upload_fill,
'creditcard_fill': SFSymbols.creditcard_fill,
'command': SFSymbols.command,
'control': SFSymbols.control,
'compass': SFSymbols.compass,
'creditcard': SFSymbols.creditcard,
'color_filter': SFSymbols.color_filter,
'crop': SFSymbols.crop,
'cube_box': SFSymbols.cube_box,
'cloud_sleet': SFSymbols.cloud_sleet,
'cube_fill': SFSymbols.cube_fill,
'cloud_sleet_fill': SFSymbols.cloud_sleet_fill,
'cube': SFSymbols.cube,
'gift_alt': SFSymbols.gift_alt,
'decrease_indent': SFSymbols.decrease_indent,
'cursor_rays': SFSymbols.cursor_rays,
'delete_left_fill': SFSymbols.delete_left_fill,
'decrease_quotelevel': SFSymbols.decrease_quotelevel,
'crop_rotate': SFSymbols.crop_rotate,
'delete_left': SFSymbols.delete_left,
'cloud_sun_bolt': SFSymbols.cloud_sun_bolt,
'delete_right': SFSymbols.delete_right,
'device_laptop': SFSymbols.device_laptop,
'cloud_sun_rain': SFSymbols.cloud_sun_rain,
'graph_circle': SFSymbols.graph_circle,
'cloud_snow_fill': SFSymbols.cloud_snow_fill,
'delete_right_fill': SFSymbols.delete_right_fill,
'device_desktop': SFSymbols.device_desktop,
'cloud_sun_rain_fill': SFSymbols.cloud_sun_rain_fill,
'device_phone_landscape': SFSymbols.device_phone_landscape,
'device_tablet_portrait': SFSymbols.device_tablet_portrait,
'hand_draw': SFSymbols.hand_draw,
'chevron_right_circle': SFSymbols.chevron_right_circle,
'hand_raised_fill': SFSymbols.hand_raised_fill,
'divide_circle_fill': SFSymbols.divide_circle_fill,
'cloud_upload': SFSymbols.cloud_upload,
'divide_circle': SFSymbols.divide_circle,
'divide_square_fill': SFSymbols.divide_square_fill,
'divide': SFSymbols.divide,
'dial_fill': SFSymbols.dial_fill,
'divide_square': SFSymbols.divide_square,
'doc_chart': SFSymbols.doc_chart,
'circle_bottomthird_split': SFSymbols.circle_bottomthird_split,
'doc_checkmark_fill': SFSymbols.doc_checkmark_fill,
'doc_fill': SFSymbols.doc_fill,
'cloud_snow': SFSymbols.cloud_snow,
'doc_append': SFSymbols.doc_append,
'doc_circle': SFSymbols.doc_circle,
'doc_circle_fill': SFSymbols.doc_circle_fill,
'doc_chart_fill': SFSymbols.doc_chart_fill,
'doc_on_doc_fill': SFSymbols.doc_on_doc_fill,
'doc_on_clipboard_fill': SFSymbols.doc_on_clipboard_fill,
'doc_checkmark': SFSymbols.doc_checkmark,
'doc_on_doc': SFSymbols.doc_on_doc,
'increase_indent': SFSymbols.increase_indent,
'doc_person_fill': SFSymbols.doc_person_fill,
'doc_plaintext': SFSymbols.doc_plaintext,
'doc_text_fill': SFSymbols.doc_text_fill,
'doc_text': SFSymbols.doc_text,
'doc': SFSymbols.doc,
'doc_richtext': SFSymbols.doc_richtext,
'dot_square_fill': SFSymbols.dot_square_fill,
'dot_square': SFSymbols.dot_square,
'dot_radiowaves_right': SFSymbols.dot_radiowaves_right,
'download_circle': SFSymbols.download_circle,
'doc_on_clipboard': SFSymbols.doc_on_clipboard,
'download_circle_fill': SFSymbols.download_circle_fill,
'exclamationmark_square_fill': SFSymbols.exclamationmark_square_fill,
'exclamationmark_square': SFSymbols.exclamationmark_square,
'eye_fill': SFSymbols.eye_fill,
'drop_triangle_fill': SFSymbols.drop_triangle_fill,
'eye_slash_fill': SFSymbols.eye_slash_fill,
'exclamationmark_triangle_fill': SFSymbols.exclamationmark_triangle_fill,
'eyedropper_full': SFSymbols.eyedropper_full,
'eye_slash': SFSymbols.eye_slash,
'eyedropper_halffull': SFSymbols.eyedropper_halffull,
'eye': SFSymbols.eye,
'f_cursive_circle': SFSymbols.f_cursive_circle,
'eyedropper': SFSymbols.eyedropper,
'f_cursive_circle_fill': SFSymbols.f_cursive_circle_fill,
'f_cursive': SFSymbols.f_cursive,
'flag_fill': SFSymbols.flag_fill,
'flag_circle_fill': SFSymbols.flag_circle_fill,
'drop_fill': SFSymbols.drop_fill,
'flag_circle': SFSymbols.flag_circle,
'eyeglasses': SFSymbols.eyeglasses,
'flag_slash': SFSymbols.flag_slash,
'flag_slash_fill': SFSymbols.flag_slash_fill,
'flag': SFSymbols.flag,
'flame': SFSymbols.flame,
'flame_fill': SFSymbols.flame_fill,
'floppy_disk': SFSymbols.floppy_disk,
'flowchart_fill': SFSymbols.flowchart_fill,
'dot_radiowaves_left_right': SFSymbols.dot_radiowaves_left_right,
'doc_text_viewfinder': SFSymbols.doc_text_viewfinder,
'folder_badge_minus': SFSymbols.folder_badge_minus,
'folder_circle_fill': SFSymbols.folder_circle_fill,
'folder_badge_person_crop': SFSymbols.folder_badge_person_crop,
'folder_circle': SFSymbols.folder_circle,
'lock_rotation_open': SFSymbols.lock_rotation_open,
'folder_fill_badge_person_crop': SFSymbols.folder_fill_badge_person_crop,
'folder_fill_badge_minus': SFSymbols.folder_fill_badge_minus,
'doc_text_search': SFSymbols.doc_text_search,
'expand': SFSymbols.expand,
'flowchart': SFSymbols.flowchart,
'folder': SFSymbols.folder,
'compass_fill': SFSymbols.compass_fill,
'folder_fill_badge_plus': SFSymbols.folder_fill_badge_plus,
'folder_fill': SFSymbols.folder_fill,
'forward_end_alt_fill': SFSymbols.forward_end_alt_fill,
'film': SFSymbols.film,
'forward_end': SFSymbols.forward_end,
'forward_end_fill': SFSymbols.forward_end_fill,
'forward_end_alt': SFSymbols.forward_end_alt,
'forward_fill': SFSymbols.forward_fill,
'forward': SFSymbols.forward,
'fx': SFSymbols.fx,
'gamecontroller_alt_fill': SFSymbols.gamecontroller_alt_fill,
'gamecontroller_fill': SFSymbols.gamecontroller_fill,
'dog': SFSymbols.dog,
'gear_alt_fill': SFSymbols.gear_alt_fill,
'gamecontroller': SFSymbols.gamecontroller,
'gauge_badge_minus': SFSymbols.gauge_badge_minus,
'gauge': SFSymbols.gauge,
'cube_box_fill': SFSymbols.cube_box_fill,
'gift_alt_fill': SFSymbols.gift_alt_fill,
'gift_fill': SFSymbols.gift_fill,
'gobackward_10': SFSymbols.gobackward_10,
'gift': SFSymbols.gift,
'gobackward_15': SFSymbols.gobackward_15,
'gobackward_30': SFSymbols.gobackward_30,
'gobackward_90': SFSymbols.gobackward_90,
'gobackward_45': SFSymbols.gobackward_45,
'gobackward_75': SFSymbols.gobackward_75,
'gobackward_60': SFSymbols.gobackward_60,
'gobackward_minus': SFSymbols.gobackward_minus,
'function': SFSymbols.function,
'gobackward': SFSymbols.gobackward,
'goforward_30': SFSymbols.goforward_30,
'goforward_15': SFSymbols.goforward_15,
'goforward_10': SFSymbols.goforward_10,
'goforward_45': SFSymbols.goforward_45,
'goforward_60': SFSymbols.goforward_60,
'goforward_90': SFSymbols.goforward_90,
'gauge_badge_plus': SFSymbols.gauge_badge_plus,
'goforward_plus': SFSymbols.goforward_plus,
'goforward': SFSymbols.goforward,
'goforward_75': SFSymbols.goforward_75,
'gear_alt': SFSymbols.gear_alt,
'desktopcomputer': SFSymbols.desktopcomputer,
'graph_square_fill': SFSymbols.graph_square_fill,
'graph_square': SFSymbols.graph_square,
'graph_circle_fill': SFSymbols.graph_circle_fill,
'greaterthan_square': SFSymbols.greaterthan_square,
'grid_circle': SFSymbols.grid_circle,
'globe': SFSymbols.globe,
'device_tablet_landscape': SFSymbols.device_tablet_landscape,
'hand_point_left_fill': SFSymbols.hand_point_left_fill,
'grid_circle_fill': SFSymbols.grid_circle_fill,
'gear': SFSymbols.gear,
'grid': SFSymbols.grid,
'greaterthan': SFSymbols.greaterthan,
'hand_point_right_fill': SFSymbols.hand_point_right_fill,
'hand_point_left': SFSymbols.hand_point_left,
'dial': SFSymbols.dial,
'hand_raised_slash_fill': SFSymbols.hand_raised_slash_fill,
'hand_raised': SFSymbols.hand_raised,
'hand_thumbsdown_fill': SFSymbols.hand_thumbsdown_fill,
'hand_raised_slash': SFSymbols.hand_raised_slash,
'hand_thumbsdown': SFSymbols.hand_thumbsdown,
'heart_circle_fill': SFSymbols.heart_circle_fill,
'hand_thumbsup_fill': SFSymbols.hand_thumbsup_fill,
'hare_fill': SFSymbols.hare_fill,
'heart_fill': SFSymbols.heart_fill,
'hand_thumbsup': SFSymbols.hand_thumbsup,
'heart_circle': SFSymbols.heart_circle,
'heart_slash_circle_fill': SFSymbols.heart_slash_circle_fill,
'heart_slash_fill': SFSymbols.heart_slash_fill,
'heart_slash': SFSymbols.heart_slash,
'heart_slash_circle': SFSymbols.heart_slash_circle,
'heart': SFSymbols.heart,
'hexagon_fill': SFSymbols.hexagon_fill,
'helm': SFSymbols.helm,
'hifispeaker': SFSymbols.hifispeaker,
'hexagon': SFSymbols.hexagon,
'hourglass': SFSymbols.hourglass,
'hourglass_bottomhalf_fill': SFSymbols.hourglass_bottomhalf_fill,
'hourglass_tophalf_fill': SFSymbols.hourglass_tophalf_fill,
'house_alt': SFSymbols.house_alt,
'house': SFSymbols.house,
'guitars': SFSymbols.guitars,
'person_crop_square_fill': SFSymbols.person_crop_square_fill,
'info_circle': SFSymbols.info_circle,
'doc_person': SFSymbols.doc_person,
'infinite': SFSymbols.infinite,
'house_fill': SFSymbols.house_fill,
'info_circle_fill': SFSymbols.info_circle_fill,
'hurricane': SFSymbols.hurricane,
'italic': SFSymbols.italic,
'info': SFSymbols.info,
'lasso': SFSymbols.lasso,
'largecircle_fill_circle': SFSymbols.largecircle_fill_circle,
'hare': SFSymbols.hare,
'layers_alt_fill': SFSymbols.layers_alt_fill,
'drop_triangle': SFSymbols.drop_triangle,
'eject_fill': SFSymbols.eject_fill,
'ear': SFSymbols.ear,
'eject': SFSymbols.eject,
'ellipses_bubble_fill': SFSymbols.ellipses_bubble_fill,
'ellipsis_circle': SFSymbols.ellipsis_circle,
'ellipsis_circle_fill': SFSymbols.ellipsis_circle_fill,
'ellipsis_vertical': SFSymbols.ellipsis_vertical,
'ellipsis_vertical_circle_fill': SFSymbols.ellipsis_vertical_circle_fill,
'cloud_fill': SFSymbols.cloud_fill,
'ellipses_bubble': SFSymbols.ellipses_bubble,
'ellipsis_vertical_circle': SFSymbols.ellipsis_vertical_circle,
'envelope_badge_fill': SFSymbols.envelope_badge_fill,
'cloud_fog_fill': SFSymbols.cloud_fog_fill,
'ellipsis': SFSymbols.ellipsis,
'envelope_circle_fill': SFSymbols.envelope_circle_fill,
'envelope_open_fill': SFSymbols.envelope_open_fill,
'envelope_fill': SFSymbols.envelope_fill,
'envelope_open': SFSymbols.envelope_open,
'envelope': SFSymbols.envelope,
'equal_circle': SFSymbols.equal_circle,
'equal_circle_fill': SFSymbols.equal_circle_fill,
'equal': SFSymbols.equal,
'envelope_circle': SFSymbols.envelope_circle,
'checkmark_alt': SFSymbols.checkmark_alt,
'equal_square': SFSymbols.equal_square,
'exclamationmark_bubble_fill': SFSymbols.exclamationmark_bubble_fill,
'exclamationmark_bubble': SFSymbols.exclamationmark_bubble,
'layers_fill': SFSymbols.layers_fill,
'escape': SFSymbols.escape,
'layers': SFSymbols.layers,
'drop': SFSymbols.drop,
'lessthan_circle': SFSymbols.lessthan_circle,
'lightbulb_slash_fill': SFSymbols.lightbulb_slash_fill,
'lightbulb': SFSymbols.lightbulb,
'light_min': SFSymbols.light_min,
'lessthan': SFSymbols.lessthan,
'lightbulb_fill': SFSymbols.lightbulb_fill,
'lessthan_square': SFSymbols.lessthan_square,
'lessthan_circle_fill': SFSymbols.lessthan_circle_fill,
'light_max': SFSymbols.light_max,
'lightbulb_slash': SFSymbols.lightbulb_slash,
'exclamationmark_triangle': SFSymbols.exclamationmark_triangle,
'line_horizontal_3_decrease_circle_fill': SFSymbols.line_horizontal_3_decrease_circle_fill,
'line_horizontal_3': SFSymbols.line_horizontal_3,
'layers_alt': SFSymbols.layers_alt,
'line_horizontal_3_decrease_circle': SFSymbols.line_horizontal_3_decrease_circle,
'link_circle': SFSymbols.link_circle,
'link_circle_fill': SFSymbols.link_circle_fill,
'line_horizontal_3_decrease': SFSymbols.line_horizontal_3_decrease,
'link': SFSymbols.link,
'list_bullet_indent': SFSymbols.list_bullet_indent,
'list_bullet_below_rectangle': SFSymbols.list_bullet_below_rectangle,
'list_bullet': SFSymbols.list_bullet,
'location_north': SFSymbols.location_north,
'list_dash': SFSymbols.list_dash,
'location': SFSymbols.location,
'keyboard': SFSymbols.keyboard,
'location_slash_fill': SFSymbols.location_slash_fill,
'location_slash': SFSymbols.location_slash,
'lock_circle_fill': SFSymbols.lock_circle_fill,
'lock_circle': SFSymbols.lock_circle,
'lock_fill': SFSymbols.lock_fill,
'rectangle_fill_on_rectangle_fill': SFSymbols.rectangle_fill_on_rectangle_fill,
'folder_badge_plus': SFSymbols.folder_badge_plus,
'lock_open_fill': SFSymbols.lock_open_fill,
'lock_open': SFSymbols.lock_open,
'lock_shield_fill': SFSymbols.lock_shield_fill,
'lock_shield': SFSymbols.lock_shield,
'lock_slash': SFSymbols.lock_slash,
'lock_slash_fill': SFSymbols.lock_slash_fill,
'lock': SFSymbols.lock,
'rectangle_on_rectangle': SFSymbols.rectangle_on_rectangle,
'logo_facebook': SFSymbols.logo_facebook,
'film_fill': SFSymbols.film_fill,
'logo_instagram': SFSymbols.logo_instagram,
'logo_google': SFSymbols.logo_google,
'logo_googleplus': SFSymbols.logo_googleplus,
'logo_github': SFSymbols.logo_github,
'logo_ios': SFSymbols.logo_ios,
'list_number_rtl': SFSymbols.list_number_rtl,
'logo_twitter': SFSymbols.logo_twitter,
'logo_linkedin': SFSymbols.logo_linkedin,
'logo_windows': SFSymbols.logo_windows,
'macwindow': SFSymbols.macwindow,
'list_number': SFSymbols.list_number,
'map_fill': SFSymbols.map_fill,
'map_pin': SFSymbols.map_pin,
'map_pin_ellipse': SFSymbols.map_pin_ellipse,
'map': SFSymbols.map,
'memories_badge_minus': SFSymbols.memories_badge_minus,
'menu': SFSymbols.menu,
'logo_android': SFSymbols.logo_android,
'memories': SFSymbols.memories,
'memories_badge_plus': SFSymbols.memories_badge_plus,
'logo_google_text': SFSymbols.logo_google_text,
'minus_circle_fill': SFSymbols.minus_circle_fill,
'metronome': SFSymbols.metronome,
'mic_circle_fill': SFSymbols.mic_circle_fill,
'mic_fill': SFSymbols.mic_fill,
'mic_circle': SFSymbols.mic_circle,
'minus_circle': SFSymbols.minus_circle,
'minus_rectangle': SFSymbols.minus_rectangle,
'minus': SFSymbols.minus,
'logo_macos': SFSymbols.logo_macos,
'money_dollar_circle': SFSymbols.money_dollar_circle,
'minus_square': SFSymbols.minus_square,
'money_dollar_circle_fill': SFSymbols.money_dollar_circle_fill,
'minus_rectangle_fill': SFSymbols.minus_rectangle_fill,
'mic_slash': SFSymbols.mic_slash,
'minus_slash_plus': SFSymbols.minus_slash_plus,
'money_dollar': SFSymbols.money_dollar,
'money_euro_circle': SFSymbols.money_euro_circle,
'minus_square_fill': SFSymbols.minus_square_fill,
'moon_fill': SFSymbols.moon_fill,
'money_euro': SFSymbols.money_euro,
'money_euro_circle_fill': SFSymbols.money_euro_circle_fill,
'mic': SFSymbols.mic,
'money_pound_circle_fill': SFSymbols.money_pound_circle_fill,
'moon_zzz_fill': SFSymbols.moon_zzz_fill,
'moon': SFSymbols.moon,
'moon_stars_fill': SFSymbols.moon_stars_fill,
'moon_stars': SFSymbols.moon_stars,
'moon_zzz': SFSymbols.moon_zzz,
'multiply_circle_fill': SFSymbols.multiply_circle_fill,
'multiply_square': SFSymbols.multiply_square,
'smallcircle_fill_circle_fill': SFSymbols.smallcircle_fill_circle_fill,
'multiply_circle': SFSymbols.multiply_circle,
'map_pin_slash': SFSymbols.map_pin_slash,
'multiply': SFSymbols.multiply,
'music_house_fill': SFSymbols.music_house_fill,
'music_mic': SFSymbols.music_mic,
'music_note_2': SFSymbols.music_note_2,
'music_house': SFSymbols.music_house,
'music_note': SFSymbols.music_note,
'nosign': SFSymbols.nosign,
'number_square_fill': SFSymbols.number_square_fill,
'greaterthan_square_fill': SFSymbols.greaterthan_square_fill,
'greaterthan_circle': SFSymbols.greaterthan_circle,
'number_circle_fill': SFSymbols.number_circle_fill,
'multiply_square_fill': SFSymbols.multiply_square_fill,
'number': SFSymbols.number,
'hammer': SFSymbols.hammer,
'option': SFSymbols.option,
'music_albums': SFSymbols.music_albums,
'sort_up': SFSymbols.sort_up,
'number_circle': SFSymbols.number_circle,
'hand_draw_fill': SFSymbols.hand_draw_fill,
'pano_fill': SFSymbols.pano_fill,
'move': SFSymbols.move,
'logo_android_text': SFSymbols.logo_android_text,
'paintbrush_fill': SFSymbols.paintbrush_fill,
'paintbrush': SFSymbols.paintbrush,
'number_square': SFSymbols.number_square,
'hand_point_right': SFSymbols.hand_point_right,
'paperclip': SFSymbols.paperclip,
'paperplane': SFSymbols.paperplane,
'pause_rectangle': SFSymbols.pause_rectangle,
'paragraph': SFSymbols.paragraph,
'paperplane_fill': SFSymbols.paperplane_fill,
'pause_fill': SFSymbols.pause_fill,
'pause_circle_fill': SFSymbols.pause_circle_fill,
'pencil': SFSymbols.pencil,
'logo_microsoft': SFSymbols.logo_microsoft,
'pencil_ellipsis_rectangle': SFSymbols.pencil_ellipsis_rectangle,
'pause_rectangle_fill': SFSymbols.pause_rectangle_fill,
'pencil_slash': SFSymbols.pencil_slash,
'pencil_circle': SFSymbols.pencil_circle,
'pause': SFSymbols.pause,
'pencil_outline': SFSymbols.pencil_outline,
'pause_circle': SFSymbols.pause_circle,
'person_crop_circle_badge_minus': SFSymbols.person_crop_circle_badge_minus,
'person_crop_circle_fill_badge_checkmark': SFSymbols.person_crop_circle_fill_badge_checkmark,
'person_crop_circle_fill_badge_minus': SFSymbols.person_crop_circle_fill_badge_minus,
'pencil_circle_fill': SFSymbols.pencil_circle_fill,
'person_crop_circle_badge_plus': SFSymbols.person_crop_circle_badge_plus,
'person_crop_circle_fill_badge_exclam': SFSymbols.person_crop_circle_fill_badge_exclam,
'person_crop_circle_badge_xmark': SFSymbols.person_crop_circle_badge_xmark,
'person_crop_rectangle_fill': SFSymbols.person_crop_rectangle_fill,
'music_note_list': SFSymbols.music_note_list,
'person_crop_circle_fill_badge_xmark': SFSymbols.person_crop_circle_fill_badge_xmark,
'person_fill': SFSymbols.person_fill,
'person_crop_circle_fill': SFSymbols.person_crop_circle_fill,
'person': SFSymbols.person,
'person_crop_rectangle': SFSymbols.person_crop_rectangle,
'person_crop_circle': SFSymbols.person_crop_circle,
'person_crop_circle_fill_badge_plus': SFSymbols.person_crop_circle_fill_badge_plus,
'perspective': SFSymbols.perspective,
'personalhotspot': SFSymbols.personalhotspot,
'increase_quotelevel': SFSymbols.increase_quotelevel,
'house_alt_fill': SFSymbols.house_alt_fill,
'phone_arrow_down_left': SFSymbols.phone_arrow_down_left,
'person_crop_square': SFSymbols.person_crop_square,
'phone_arrow_up_right': SFSymbols.phone_arrow_up_right,
'square_stack': SFSymbols.square_stack,
'phone_arrow_right': SFSymbols.phone_arrow_right,
'phone_circle': SFSymbols.phone_circle,
'phone_down_circle_fill': SFSymbols.phone_down_circle_fill,
'phone_down_circle': SFSymbols.phone_down_circle,
'square_stack_3d_down_right_fill': SFSymbols.square_stack_3d_down_right_fill,
'photo_fill_on_rectangle_fill': SFSymbols.photo_fill_on_rectangle_fill,
'phone': SFSymbols.phone,
'photo_on_rectangle': SFSymbols.photo_on_rectangle,
'photo': SFSymbols.photo,
'phone_down': SFSymbols.phone_down,
'phone_fill_arrow_right': SFSymbols.phone_fill_arrow_right,
'photo_fill': SFSymbols.photo_fill,
'phone_fill_arrow_down_left': SFSymbols.phone_fill_arrow_down_left,
'pano': SFSymbols.pano,
'piano': SFSymbols.piano,
'placemark_fill': SFSymbols.placemark_fill,
'pin': SFSymbols.pin,
'pin_fill': SFSymbols.pin_fill,
'pin_slash_fill': SFSymbols.pin_slash_fill,
'pin_slash': SFSymbols.pin_slash,
'placemark': SFSymbols.placemark,
'play_fill': SFSymbols.play_fill,
'play_circle_fill': SFSymbols.play_circle_fill,
'phone_badge_plus': SFSymbols.phone_badge_plus,
'play_rectangle': SFSymbols.play_rectangle,
'exclamationmark_circle': SFSymbols.exclamationmark_circle,
'playpause_fill': SFSymbols.playpause_fill,
'exclamationmark_octagon_fill': SFSymbols.exclamationmark_octagon_fill,
'play_circle': SFSymbols.play_circle,
'exclamationmark_circle_fill': SFSymbols.exclamationmark_circle_fill,
'exclamationmark_shield_fill': SFSymbols.exclamationmark_shield_fill,
'paw': SFSymbols.paw,
'exclamationmark_shield': SFSymbols.exclamationmark_shield,
'exclamationmark': SFSymbols.exclamationmark,
'playpause': SFSymbols.playpause,
'cloud_moon': SFSymbols.cloud_moon,
'lessthan_square_fill': SFSymbols.lessthan_square_fill,
'plus_app': SFSymbols.plus_app,
'keyboard_chevron_compact_down': SFSymbols.keyboard_chevron_compact_down,
'play_rectangle_fill': SFSymbols.play_rectangle_fill,
'plus_bubble': SFSymbols.plus_bubble,
'plus_rectangle_fill': SFSymbols.plus_rectangle_fill,
'plus_circle_fill': SFSymbols.plus_circle_fill,
'plus_rectangle_fill_on_rectangle_fill': SFSymbols.plus_rectangle_fill_on_rectangle_fill,
'plus_circle': SFSymbols.plus_circle,
'plus_rectangle': SFSymbols.plus_rectangle,
'plus': SFSymbols.plus,
'plus_square_fill': SFSymbols.plus_square_fill,
'plus_rectangle_on_rectangle': SFSymbols.plus_rectangle_on_rectangle,
'plus_slash_minus': SFSymbols.plus_slash_minus,
'plus_square_on_square': SFSymbols.plus_square_on_square,
'plusminus': SFSymbols.plusminus,
'plusminus_circle': SFSymbols.plusminus_circle,
'plus_square_fill_on_square_fill': SFSymbols.plus_square_fill_on_square_fill,
'poultry_leg': SFSymbols.poultry_leg,
'printer': SFSymbols.printer,
'printer_fill': SFSymbols.printer_fill,
'plus_bubble_fill': SFSymbols.plus_bubble_fill,
'plusminus_circle_fill': SFSymbols.plusminus_circle_fill,
'power': SFSymbols.power,
'question_circle_fill': SFSymbols.question_circle_fill,
'sun_dust_fill': SFSymbols.sun_dust_fill,
'purchased_circle_fill': SFSymbols.purchased_circle_fill,
'purchased': SFSymbols.purchased,
'question_circle': SFSymbols.question_circle,
'question_diamond_fill': SFSymbols.question_diamond_fill,
'question_diamond': SFSymbols.question_diamond,
'play': SFSymbols.play,
'question_square': SFSymbols.question_square,
'purchased_circle': SFSymbols.purchased_circle,
'question': SFSymbols.question,
'question_square_fill': SFSymbols.question_square_fill,
'radiowaves_left': SFSymbols.radiowaves_left,
'location_north_line_fill': SFSymbols.location_north_line_fill,
'quote_bubble_fill': SFSymbols.quote_bubble_fill,
'location_fill': SFSymbols.location_fill,
'location_circle_fill': SFSymbols.location_circle_fill,
'quote_bubble': SFSymbols.quote_bubble,
'location_circle': SFSymbols.location_circle,
'recordingtape': SFSymbols.recordingtape,
'location_north_fill': SFSymbols.location_north_fill,
'rectangle_3_offgrid_fill': SFSymbols.rectangle_3_offgrid_fill,
'rectangle_arrow_up_right_arrow_down_left_slash': SFSymbols.rectangle_arrow_up_right_arrow_down_left_slash,
'rectangle_3_offgrid': SFSymbols.rectangle_3_offgrid,
'rays': SFSymbols.rays,
'rectangle_arrow_up_right_arrow_down_left': SFSymbols.rectangle_arrow_up_right_arrow_down_left,
'plus_app_fill': SFSymbols.plus_app_fill,
'leaf_arrow_circlepath': SFSymbols.leaf_arrow_circlepath,
'qrcode': SFSymbols.qrcode,
'rectangle_fill_on_rectangle_angled_fill': SFSymbols.rectangle_fill_on_rectangle_angled_fill,
'rectangle_badge_checkmark': SFSymbols.rectangle_badge_checkmark,
'plus_square': SFSymbols.plus_square,
'radiowaves_right': SFSymbols.radiowaves_right,
'qrcode_viewfinder': SFSymbols.qrcode_viewfinder,
'rectangle_fill_badge_checkmark': SFSymbols.rectangle_fill_badge_checkmark,
'lock_rotation': SFSymbols.lock_rotation,
'rectangle_fill_badge_xmark': SFSymbols.rectangle_fill_badge_xmark,
'rectangle_expand_vertical': SFSymbols.rectangle_expand_vertical,
'rectangle_grid_2x2_fill': SFSymbols.rectangle_grid_2x2_fill,
'rectangle_badge_xmark': SFSymbols.rectangle_badge_xmark,
'rectangle_compress_vertical': SFSymbols.rectangle_compress_vertical,
'rectangle_fill': SFSymbols.rectangle_fill,
'rectangle_grid_1x2_fill': SFSymbols.rectangle_grid_1x2_fill,
'location_north_line': SFSymbols.location_north_line,
'rectangle_grid_1x2': SFSymbols.rectangle_grid_1x2,
'rectangle_grid_3x2_fill': SFSymbols.rectangle_grid_3x2_fill,
'rectangle_dock': SFSymbols.rectangle_dock,
'logo_apple': SFSymbols.logo_apple,
'rectangle_grid_2x2': SFSymbols.rectangle_grid_2x2,
'rectangle_on_rectangle_angled': SFSymbols.rectangle_on_rectangle_angled,
'rectangle_stack_badge_minus': SFSymbols.rectangle_stack_badge_minus,
'rectangle_split_3x1_fill': SFSymbols.rectangle_split_3x1_fill,
'rectangle_split_3x3_fill': SFSymbols.rectangle_split_3x3_fill,
'rectangle_stack_badge_person_crop': SFSymbols.rectangle_stack_badge_person_crop,
'rectangle_split_3x3': SFSymbols.rectangle_split_3x3,
'rectangle_paperclip': SFSymbols.rectangle_paperclip,
'rectangle_stack_badge_plus': SFSymbols.rectangle_stack_badge_plus,
'rectangle_stack_fill_badge_person_crop': SFSymbols.rectangle_stack_fill_badge_person_crop,
'logo_rss': SFSymbols.logo_rss,
'rectangle_stack_fill': SFSymbols.rectangle_stack_fill,
'rectangle_stack_fill_badge_minus': SFSymbols.rectangle_stack_fill_badge_minus,
'rectangle': SFSymbols.rectangle,
'rectangle_split_3x1': SFSymbols.rectangle_split_3x1,
'rectangle_stack': SFSymbols.rectangle_stack,
'rectangle_stack_fill_badge_plus': SFSymbols.rectangle_stack_fill_badge_plus,
'rectangle_stack_person_crop': SFSymbols.rectangle_stack_person_crop,
'rectangle_stack_person_crop_fill': SFSymbols.rectangle_stack_person_crop_fill,
'repeat': SFSymbols.repeat,
'resize_h': SFSymbols.resize_h,
'resize_v': SFSymbols.resize_v,
'repeat_1': SFSymbols.repeat_1,
'resize': SFSymbols.resize,
'return_': SFSymbols.return_,
'rectangle_grid_3x2': SFSymbols.rectangle_grid_3x2,
'rosette': SFSymbols.rosette,
'rocket_fill': SFSymbols.rocket_fill,
'mic_slash_fill': SFSymbols.mic_slash_fill,
'rotate_left_fill': SFSymbols.rotate_left_fill,
'scissors_alt': SFSymbols.scissors_alt,
'rhombus': SFSymbols.rhombus,
'search': SFSymbols.search,
'rotate_left': SFSymbols.rotate_left,
'selection_pin_in_out': SFSymbols.selection_pin_in_out,
'rotate_right': SFSymbols.rotate_right,
'shield_fill': SFSymbols.shield_fill,
'scissors': SFSymbols.scissors,
'rotate_right_fill': SFSymbols.rotate_right_fill,
'shield_slash_fill': SFSymbols.shield_slash_fill,
'money_pound': SFSymbols.money_pound,
'money_pound_circle': SFSymbols.money_pound_circle,
'rhombus_fill': SFSymbols.rhombus_fill,
'shield_slash': SFSymbols.shield_slash,
'scope': SFSymbols.scope,
'money_yen_circle_fill': SFSymbols.money_yen_circle_fill,
'money_rubl_circle': SFSymbols.money_rubl_circle,
'money_rubl': SFSymbols.money_rubl,
'waveform_path_badge_minus': SFSymbols.waveform_path_badge_minus,
'money_yen_circle': SFSymbols.money_yen_circle,
'moon_circle': SFSymbols.moon_circle,
'money_yen': SFSymbols.money_yen,
'shift_fill': SFSymbols.shift_fill,
'moon_circle_fill': SFSymbols.moon_circle_fill,
'shield': SFSymbols.shield,
'rocket': SFSymbols.rocket,
'shift': SFSymbols.shift,
'sidebar_right': SFSymbols.sidebar_right,
'sidebar_left': SFSymbols.sidebar_left,
'shuffle': SFSymbols.shuffle,
'skew': SFSymbols.skew,
'slash_circle': SFSymbols.slash_circle,
'wand_stars_inverse': SFSymbols.wand_stars_inverse,
'slash_circle_fill': SFSymbols.slash_circle_fill,
'slider_horizontal_below_rectangle': SFSymbols.slider_horizontal_below_rectangle,
'smallcircle_circle_fill': SFSymbols.smallcircle_circle_fill,
'slider_horizontal_3': SFSymbols.slider_horizontal_3,
'music_albums_fill': SFSymbols.music_albums_fill,
'smallcircle_circle': SFSymbols.smallcircle_circle,
'smiley': SFSymbols.smiley,
'smiley_fill': SFSymbols.smiley_fill,
'smallcircle_fill_circle': SFSymbols.smallcircle_fill_circle,
'greaterthan_circle_fill': SFSymbols.greaterthan_circle_fill,
'smoke_fill': SFSymbols.smoke_fill,
'sort_down_circle_fill': SFSymbols.sort_down_circle_fill,
'smoke': SFSymbols.smoke,
'sort_down': SFSymbols.sort_down,
'sort_down_circle': SFSymbols.sort_down_circle,
'sort_up_circle_fill': SFSymbols.sort_up_circle_fill,
'sort_up_circle': SFSymbols.sort_up_circle,
'hammer_fill': SFSymbols.hammer_fill,
'signature': SFSymbols.signature,
'sparkles': SFSymbols.sparkles,
'speaker_1_fill': SFSymbols.speaker_1_fill,
'speaker_1': SFSymbols.speaker_1,
'speaker_2': SFSymbols.speaker_2,
'speaker_2_fill': SFSymbols.speaker_2_fill,
'speaker_fill': SFSymbols.speaker_fill,
'slowmo': SFSymbols.slowmo,
'speaker_3_fill': SFSymbols.speaker_3_fill,
'speaker_slash_fill_rtl': SFSymbols.speaker_slash_fill_rtl,
'speaker_slash_fill': SFSymbols.speaker_slash_fill,
'speaker_3': SFSymbols.speaker_3,
'speaker_slash': SFSymbols.speaker_slash,
'speaker_slash_rtl': SFSymbols.speaker_slash_rtl,
'speaker_zzz_fill': SFSymbols.speaker_zzz_fill,
'sportscourt_fill': SFSymbols.sportscourt_fill,
'speaker': SFSymbols.speaker,
'snow': SFSymbols.snow,
'sportscourt': SFSymbols.sportscourt,
'square_arrow_down_on_square_fill': SFSymbols.square_arrow_down_on_square_fill,
'square_arrow_down_fill': SFSymbols.square_arrow_down_fill,
'speaker_zzz_rtl': SFSymbols.speaker_zzz_rtl,
'sun_haze': SFSymbols.sun_haze,
'sun_haze_fill': SFSymbols.sun_haze_fill,
'suit_heart': SFSymbols.suit_heart,
'speaker_zzz': SFSymbols.speaker_zzz,
'star_circle_fill': SFSymbols.star_circle_fill,
'sun_min': SFSymbols.sun_min,
'text_cursor': SFSymbols.text_cursor,
'text_alignright': SFSymbols.text_alignright,
'triangle_fill': SFSymbols.triangle_fill,
'phone_fill_badge_plus': SFSymbols.phone_fill_badge_plus,
'text_justify': SFSymbols.text_justify,
'tray_arrow_up_fill': SFSymbols.tray_arrow_up_fill,
'tray_arrow_down': SFSymbols.tray_arrow_down,
'textbox': SFSymbols.textbox,
'triangle': SFSymbols.triangle,
'text_badge_plus': SFSymbols.text_badge_plus,
'person_2_square_stack_fill': SFSymbols.person_2_square_stack_fill,
'square_stack_3d_up': SFSymbols.square_stack_3d_up,
'tray_full': SFSymbols.tray_full,
'search_circle': SFSymbols.search_circle,
'person_circle': SFSymbols.person_circle,
'videocam_circle_fill': SFSymbols.videocam_circle_fill,
'zzz': SFSymbols.zzz,
'trash_slash': SFSymbols.trash_slash,
'person_badge_plus_fill': SFSymbols.person_badge_plus_fill,
'square_arrow_up_on_square': SFSymbols.square_arrow_up_on_square,
'umbrella': SFSymbols.umbrella,
'square_favorites_alt': SFSymbols.square_favorites_alt,
'xmark_square': SFSymbols.xmark_square,
'wand_rays': SFSymbols.wand_rays,
'wind': SFSymbols.wind,
'square_arrow_down_on_square': SFSymbols.square_arrow_down_on_square,
'waveform_path_badge_plus': SFSymbols.waveform_path_badge_plus,
'person_2_square_stack': SFSymbols.person_2_square_stack,
'waveform': SFSymbols.waveform,
'hifispeaker_fill': SFSymbols.hifispeaker_fill,
'square_arrow_up_on_square_fill': SFSymbols.square_arrow_up_on_square_fill,
'square_arrow_left': SFSymbols.square_arrow_left,
'viewfinder_circle': SFSymbols.viewfinder_circle,
'viewfinder_circle_fill': SFSymbols.viewfinder_circle_fill,
'xmark_octagon_fill': SFSymbols.xmark_octagon_fill,
'xmark_shield_fill': SFSymbols.xmark_shield_fill,
'videocam_fill': SFSymbols.videocam_fill,
'phone_fill_arrow_up_right': SFSymbols.phone_fill_arrow_up_right,
'stop': SFSymbols.stop,
'shield_lefthalf_fill': SFSymbols.shield_lefthalf_fill,
'person_badge_plus': SFSymbols.person_badge_plus,
'person_2': SFSymbols.person_2,
'square_arrow_up': SFSymbols.square_arrow_up,
'tv': SFSymbols.tv,
'scribble': SFSymbols.scribble,
'uiwindow_split_2x1': SFSymbols.uiwindow_split_2x1,
'viewfinder': SFSymbols.viewfinder,
'zoom_out': SFSymbols.zoom_out,
'tv_music_note_fill': SFSymbols.tv_music_note_fill,
'square_arrow_up_fill': SFSymbols.square_arrow_up_fill,
'view_2d': SFSymbols.view_2d,
'speedometer': SFSymbols.speedometer,
'square_fill_line_vertical_square_fill': SFSymbols.square_fill_line_vertical_square_fill,
'star_lefthalf_fill': SFSymbols.star_lefthalf_fill,
'square_grid_2x2_fill': SFSymbols.square_grid_2x2_fill,
'suit_heart_fill': SFSymbols.suit_heart_fill,
'square_fill': SFSymbols.square_fill,
'square_arrow_left_fill': SFSymbols.square_arrow_left_fill,
'star_fill': SFSymbols.star_fill,
'wrench_fill': SFSymbols.wrench_fill,
'staroflife': SFSymbols.staroflife,
'staroflife_fill': SFSymbols.staroflife_fill,
'square': SFSymbols.square,
'square_fill_on_square_fill': SFSymbols.square_fill_on_square_fill,
'star_slash': SFSymbols.star_slash,
'sun_max': SFSymbols.sun_max,
'sun_max_fill': SFSymbols.sun_max_fill,
'star': SFSymbols.star,
'text_aligncenter': SFSymbols.text_aligncenter,
'suit_club': SFSymbols.suit_club,
'timer': SFSymbols.timer,
'triangle_lefthalf_fill': SFSymbols.triangle_lefthalf_fill,
'text_justifyleft': SFSymbols.text_justifyleft,
'textformat_alt': SFSymbols.textformat_alt,
'today_fill': SFSymbols.today_fill,
'trash_circle': SFSymbols.trash_circle,
'text_badge_minus': SFSymbols.text_badge_minus,
'star_slash_fill': SFSymbols.star_slash_fill,
'tropicalstorm': SFSymbols.tropicalstorm,
'square_stack_3d_up_slash': SFSymbols.square_stack_3d_up_slash,
'table_badge_more_fill': SFSymbols.table_badge_more_fill,
'trash': SFSymbols.trash,
'textformat_abc': SFSymbols.textformat_abc,
'table': SFSymbols.table,
'textformat': SFSymbols.textformat,
'tray_2_fill': SFSymbols.tray_2_fill,
'xmark_seal': SFSymbols.xmark_seal,
'text_bubble_fill': SFSymbols.text_bubble_fill,
'xmark_square_fill': SFSymbols.xmark_square_fill,
'person_2_alt': SFSymbols.person_2_alt,
'tree': SFSymbols.tree,
'thermometer_sun': SFSymbols.thermometer_sun,
'tortoise': SFSymbols.tortoise,
'strikethrough': SFSymbols.strikethrough,
'textformat_abc_dottedunderline': SFSymbols.textformat_abc_dottedunderline,
'trash_slash_fill': SFSymbols.trash_slash_fill,
'textformat_123': SFSymbols.textformat_123,
'sun_dust': SFSymbols.sun_dust,
'phone_down_fill': SFSymbols.phone_down_fill,
'tray': SFSymbols.tray,
'exclamationmark_octagon': SFSymbols.exclamationmark_octagon,
'text_badge_xmark': SFSymbols.text_badge_xmark,
'timer_fill': SFSymbols.timer_fill,
'tornado': SFSymbols.tornado,
'text_insert': SFSymbols.text_insert,
'textformat_superscript': SFSymbols.textformat_superscript,
'tag_circle': SFSymbols.tag_circle,
'phone_fill': SFSymbols.phone_fill,
'suit_club_fill': SFSymbols.suit_club_fill,
'ticket': SFSymbols.ticket,
'textformat_size': SFSymbols.textformat_size,
'sun_min_fill': SFSymbols.sun_min_fill,
'sum': SFSymbols.sum,
'person_badge_minus_fill': SFSymbols.person_badge_minus_fill,
'tray_arrow_down_fill': SFSymbols.tray_arrow_down_fill,
'waveform_path_ecg': SFSymbols.waveform_path_ecg,
'tv_circle_fill': SFSymbols.tv_circle_fill,
'tuningfork': SFSymbols.tuningfork,
'xmark_shield': SFSymbols.xmark_shield,
'xmark_rectangle_fill': SFSymbols.xmark_rectangle_fill,
'waveform_circle': SFSymbols.waveform_circle,
'square_split_2x1': SFSymbols.square_split_2x1,
'person_crop_circle_badge_checkmark': SFSymbols.person_crop_circle_badge_checkmark,
'upload_circle': SFSymbols.upload_circle,
'wand_rays_inverse': SFSymbols.wand_rays_inverse,
'person_badge_minus': SFSymbols.person_badge_minus,
'zoom_in': SFSymbols.zoom_in,
'wifi_exclamationmark': SFSymbols.wifi_exclamationmark,
'headphones': SFSymbols.headphones,
'xmark_circle_fill': SFSymbols.xmark_circle_fill,
'xmark_seal_fill': SFSymbols.xmark_seal_fill,
'suit_spade': SFSymbols.suit_spade,
'upload_circle_fill': SFSymbols.upload_circle_fill,
'square_grid_3x2': SFSymbols.square_grid_3x2,
'money_rubl_circle_fill': SFSymbols.money_rubl_circle_fill,
'videocam_circle': SFSymbols.videocam_circle,
'tag_circle_fill': SFSymbols.tag_circle_fill,
'textformat_subscript': SFSymbols.textformat_subscript,
'tortoise_fill': SFSymbols.tortoise_fill,
'table_fill': SFSymbols.table_fill,
'stop_circle_fill': SFSymbols.stop_circle_fill,
'text_justifyright': SFSymbols.text_justifyright,
'text_alignleft': SFSymbols.text_alignleft,
'square_favorites': SFSymbols.square_favorites,
'projective': SFSymbols.projective,
'trash_circle_fill': SFSymbols.trash_circle_fill,
'today': SFSymbols.today,
'tickets_fill': SFSymbols.tickets_fill,
'tram_fill': SFSymbols.tram_fill,
'stop_fill': SFSymbols.stop_fill,
'triangle_righthalf_fill': SFSymbols.triangle_righthalf_fill,
'tray_full_fill': SFSymbols.tray_full_fill,
'tag_fill': SFSymbols.tag_fill,
'tray_fill': SFSymbols.tray_fill,
'text_quote': SFSymbols.text_quote,
'tray_2': SFSymbols.tray_2,
'text_badge_checkmark': SFSymbols.text_badge_checkmark,
'text_append': SFSymbols.text_append,
'stopwatch_fill': SFSymbols.stopwatch_fill,
't_bubble': SFSymbols.t_bubble,
'square_fill_on_circle_fill': SFSymbols.square_fill_on_circle_fill,
'person_crop_circle_badge_exclam': SFSymbols.person_crop_circle_badge_exclam,
'sunset_fill': SFSymbols.sunset_fill,
'sunrise': SFSymbols.sunrise,
'suit_diamond_fill': SFSymbols.suit_diamond_fill,
'sunset': SFSymbols.sunset,
't_bubble_fill': SFSymbols.t_bubble_fill,
'square_righthalf_fill': SFSymbols.square_righthalf_fill,
'square_lefthalf_fill': SFSymbols.square_lefthalf_fill,
'square_line_vertical_square_fill': SFSymbols.square_line_vertical_square_fill,
'tray_arrow_up': SFSymbols.tray_arrow_up,
'square_split_1x2': SFSymbols.square_split_1x2,
'square_pencil': SFSymbols.square_pencil,
'square_on_square': SFSymbols.square_on_square,
'square_grid_2x2': SFSymbols.square_grid_2x2,
'square_line_vertical_square': SFSymbols.square_line_vertical_square,
'square_list_fill': SFSymbols.square_list_fill,
'square_stack_3d_down_right': SFSymbols.square_stack_3d_down_right,
'phone_circle_fill': SFSymbols.phone_circle_fill,
'thermometer_snowflake': SFSymbols.thermometer_snowflake,
'square_stack_3d_up_fill': SFSymbols.square_stack_3d_up_fill,
'square_split_2x2': SFSymbols.square_split_2x2,
'square_split_2x2_fill': SFSymbols.square_split_2x2_fill,
'square_stack_fill': SFSymbols.square_stack_fill,
'suit_spade_fill': SFSymbols.suit_spade_fill,
'percent': SFSymbols.percent,
'xmark_octagon': SFSymbols.xmark_octagon,
'wrench': SFSymbols.wrench,
'xmark': SFSymbols.xmark,
'search_circle_fill': SFSymbols.search_circle_fill,
'tv_fill': SFSymbols.tv_fill,
'tv_circle': SFSymbols.tv_circle,
'waveform_path': SFSymbols.waveform_path,
'square_fill_line_vertical_square': SFSymbols.square_fill_line_vertical_square,
'underline': SFSymbols.underline,
'person_circle_fill': SFSymbols.person_circle_fill,
'square_favorites_alt_fill': SFSymbols.square_favorites_alt_fill,
'square_grid_4x3_fill': SFSymbols.square_grid_4x3_fill,
'square_stack_3d_down_dottedline': SFSymbols.square_stack_3d_down_dottedline,
'square_arrow_right_fill': SFSymbols.square_arrow_right_fill,
'square_split_1x2_fill': SFSymbols.square_split_1x2_fill,
'tv_music_note': SFSymbols.tv_music_note,
'suit_diamond': SFSymbols.suit_diamond,
'star_circle': SFSymbols.star_circle,
'squares_below_rectangle': SFSymbols.squares_below_rectangle,
'wifi': SFSymbols.wifi,
'timelapse': SFSymbols.timelapse,
'waveform_circle_fill': SFSymbols.waveform_circle_fill,
'sunrise_fill': SFSymbols.sunrise_fill,
'wind_snow': SFSymbols.wind_snow,
'table_badge_more': SFSymbols.table_badge_more,
'stop_circle': SFSymbols.stop_circle,
'text_bubble': SFSymbols.text_bubble,
'ticket_fill': SFSymbols.ticket_fill,
'square_grid_3x2_fill': SFSymbols.square_grid_3x2_fill,
'thermometer': SFSymbols.thermometer,
'stopwatch': SFSymbols.stopwatch,
'person_alt': SFSymbols.person_alt,
'square_on_circle': SFSymbols.square_on_circle,
'square_pencil_fill': SFSymbols.square_pencil_fill,
'square_list': SFSymbols.square_list,
'person_3': SFSymbols.person_3,
'speaker_zzz_fill_rtl': SFSymbols.speaker_zzz_fill_rtl,
'videocam': SFSymbols.videocam,
'person_3_fill': SFSymbols.person_3_fill,
'wifi_slash': SFSymbols.wifi_slash,
'xmark_circle': SFSymbols.xmark_circle,
'square_arrow_right': SFSymbols.square_arrow_right,
'person_2_fill': SFSymbols.person_2_fill,
'xmark_rectangle': SFSymbols.xmark_rectangle,
'square_stack_3d_up_slash_fill': SFSymbols.square_stack_3d_up_slash_fill,
'umbrella_fill': SFSymbols.umbrella_fill,
'square_split_2x1_fill': SFSymbols.square_split_2x1_fill,
'trash_fill': SFSymbols.trash_fill,
'square_favorites_fill': SFSymbols.square_favorites_fill,
'square_arrow_down': SFSymbols.square_arrow_down,
'view_3d': SFSymbols.view_3d,
'person_alt_circle_fill': SFSymbols.person_alt_circle_fill,
'text_badge_star': SFSymbols.text_badge_star,
'tickets': SFSymbols.tickets,
'person_alt_circle': SFSymbols.person_alt_circle,
'wand_stars': SFSymbols.wand_stars,
'tag': SFSymbols.tag,
'airplane': SFSymbols.airplane,
};